### ISSUE TITLE
Future optimizations

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#124]
Things we know that might be faster, but that we left for now because it simplifies the code

- [ ] Move the `bitpack_array` C++ loop inside the assembly part. Gives speedup of about 5% for the `bitpack_array` function on Raspberry Pi.
- [ ] Remove the `bitpack_matrix` loop when there's no padding (i.e. `bitpack_matrix` becomes a single `bitpack_array` call).
- [ ] Decouple bitpacking bitwidth and bgemm bitwidth: we can use the 64-bit bitpacking code for 32-bit bgemm code.
- [ ] Cache RUY prepacking for weights

**Comment by lgeiger** [comment]
Closed via #443
