### ISSUE TITLE
Automate generating cartesian products in the bconv unit tests

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#279]
The test parameters at the bottom of [bconv2d_test.cc](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/tflite/tests/bconv2d_test.cc) should automatically be generated by something that generates cartesian products (like a nested `::testing::Combine`).

**Comment by lgeiger** [comment]
BConv tests have been simplified a lot in #467 so I think we can close this.
