### ISSUE TITLE
Benchmark when "bitpack after im2col" is faster

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#290]
In `tflite/kernels/bconv2d.cc` in `decide_bitpack_before_im2col` the kernel decides if it should do bitpacking before or after im2col.

Currently this is simply `if (channels_in >= bitwidth / 4)`, based on old benchmarks. A simple benchmark shows that this is no longer the correct decision boundary, it should be closer to `bitwidth/2` judging from this plot:
![plot_latency](https://user-images.githubusercontent.com/248512/76899362-a244f500-6897-11ea-8503-b5270e959698.png)

> Plot explanation: This shows inference times for our bconv2d op on an input size `(224,224)` on the Pixel 1. In the case "bitpack before im2col" then basically it doesn't matter if you have 1 or 64 input channels because they all get bitpacked into one `uint64`. Therefore that line is flat. For 32-bit there is the clear jump of going from one `uint32` to two `uint32`s but otherwise that is flat as well.

Furthermore, the proper decision probably depends on the "depth" dimension of the matrix multiplication, which has size `filter_height * filter_width * channels_in`.

We should
- benchmark if "depth" is a better indicator than `channels_in`
- benchmark if other parts of input/filter shape are relevant in this decision.

If needed (plot suggests it wont be) the kernel can also decide to use 32-bit bitpacking vs 64-bit bitpacking dynamically based on input/filter shapes.

**Comment by lgeiger** [comment]
Since #457 we will always bitpack before im2col, so this issue can be closed.
