### ISSUE TITLE
support tensorflow lite micro

### ISSUE THREAD

**Issue by king3cheung** [larq/compute-engine#345]
is it possible to support tensorflow lite micro? in IOT field,esp32,stm32f7/f4 was widely used, but  no suitable binary neworks can run on these platforms with limited resourse。

**Comment by rnusselder** [comment]
Hey! That's a great question. We at Plumerai are developing Larq Compute Engine Micro. This leverages TFLite Micro and targets Cortex-M microcontrollers for efficient BNN inference. We are currently planning to keep this closed, but I'd love to chat with you to see if we can help you. You can reach me here: roeland@plumerai.com.
Best,
Roeland

**Comment by king3cheung** [comment]
Thank you for your response,you guys are doing a great  job!  I would like to know your opinion about porting Larq Compute Engine to eps32 cam, it's a interesting and  challenging  job. I will contact you for your help if i want to start this job,if there are some other guys Interested in this question, we can discuss together.

**Comment by rnusselder** [comment]
We haven't really looked into porting Larq Compute Engine to ESP32 yet. Cortex-M was the obvious platform to start with, and there's relatively little documentation for ESP32. Anyway, it would be great to do this eventually!

**Comment by jonnor** [comment]
Any updates on this (in particular the ARM Cortex M support)? I note that there was a talk at TinyML about Larq and also microcontrollers?

**Comment by rnusselder** [comment]
It's good to hear that you watched our TinyML Talk. We're keeping our inference engine for Cortex-M (Larq Compute Engine Micro) closed source for now and it is currently only available for customers.

**Comment by jonnor** [comment]
Ok, thank you for the quick response!
