### ISSUE TITLE
Update Benchmark table in readme

### ISSUE THREAD

**Issue by lgeiger** [larq/compute-engine#358]
#350 significantly improved performance on ARM64. It would good to update the table on the readme to reflect that.

@AdamHillier I think we can take the RP4 benchmarks directly from your PR. So only the Pixel 1 benchmarks are missing, correct?

**Comment by AdamHillier** [comment]
> @AdamHillier I think we can take the RP4 benchmarks directly from your PR. So only the Pixel 1 benchmarks are missing, correct?

Yep, sounds good to me :+1:

Actually the latency numbers I got for my baseline for that PR were already a chunk better than the ones in the README, so I think we must have got a boost from something else as well, maybe the TF2.2 upgrade?

**Comment by lgeiger** [comment]
> so I think we must have got a boost from something else as well, maybe the TF2.2 upgrade?

TF 2.2 sounds likely, I think one could get even faster numbers now using the XNNPack delegate for the float32 ops, but I think that would require a bit more testing.

**Comment by lgeiger** [comment]
Closed via #359
