### ISSUE TITLE
"Slow" inference times on a raspberry pi

### ISSUE THREAD

**Issue by johnrobinsn** [larq/compute-engine#383]
Using a converted version of the provided Quicknet pretrained model from the zoo... and using an lce build (built on the rpi target itself... Make instructions).  I'm able to get inference working fine... but the time for the interpreter->Invoke() on a pi 3b+ is around ~**800ms**.  any pointers/tips on what might be going on?    I'm expecting something much closer to the ~40ms reported for the pi 4b?

Thanks in advance.

**Comment by AdamHillier** [comment]
Hey, thanks for your interest in Larq and LCE!

Just to be sure, which version of Larq Compute Engine pip package are you using to convert the model, and which version of LCE are you using to run the converted model on your Raspberry Pi (the most recent commit hash from your local clone)?

Are you using our [`benchmarking binary`](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/tflite/benchmark/README.md) to run the model and get those numbers?

**Comment by johnrobinsn** [comment]
Thanks for your response.
Here is the hash from my local git clone:
$ git show --oneline -s
7c0562a (HEAD -> master, origin/master, origin/HEAD) Make sure end2end test fail when assertions fail in C++ (#374)

To measure the performance, I'm using an lce-minimal derived test that I've created... and I'm just timing a single  interpreter->Invoke call wrapped with some calls to clock_gettime...

I've included a google drive link to the test source, a shell script that I used to build it and the  converted quicknet model file that I'm using.

https://drive.google.com/drive/folders/1oVSe6XqUQeYtvaJGlxlANd5I-O-IyNLX?usp=sharing

**Comment by AdamHillier** [comment]
Okay so the LCE version and the model both look correct.

Sorry, I forgot to ask one other thing: are you running a 64-bit OS on your Raspberry Pi? Our optimised Arm kernels are implemented for 64-bit Arm, so when using a 32-bit OS LCE falls back to reference kernels that will be quite a bit slower. The 64-bit OS we use on our Raspberry Pi boards (4B version, though it should work for 3B too) is [Manjaro](https://manjaro.org/download/arm/raspberry-pi-4/arm8-raspberry-pi-4-kde-plasma/), though any other 64-bit OS should work as well. I think that could explain the difference here.

**Comment by johnrobinsn** [comment]
Thanks Adam for the extra detail... 

I was using 32 bit build on Raspbian.

I rebuilt on Manjara 64 bit and confirm that I'm seeing around 73ms inference time with the same quicknet model on my Raspberry Pi 3b+ using 4 threads..

**Any plans for improving the 32bit performance?** 

Great project thanks for sharing.

**Comment by AdamHillier** [comment]
Great to hear :)

At the moment I don't think 32-bit optimised kernels are on our radar. The implementation would be trickier; for example on Arm32 there are half the number of NEON vector registers that we need to use in our assembly kernels. There would also be an increased maintenance burden. Conversely, almost all of our target devices of interest are 64-bit Arm (and 64-bit devices will only become more prevelant over time). This includes all the recent Raspberry Pis, despite not having 64-bit OSs by default. In the Raspberry Pi case I appreciate that it's a little confusing, so we've made the limitation clearer in our docs in larq/docs#119.

That said, we would welcome any external contributions to improve 32-bit performance in LCE!

**Comment by lgeiger** [comment]
I am closing this issue since the original problem has been resolved. @johnrobinsn Feel free to open a new issue if we are missing a case where upgrading to a 64-bit OS would not be possible.
