### ISSUE TITLE
Error in replicating Quicknet benchmark results on Raspberry Pi 4 B

### ISSUE THREAD

**Issue by kirstenhipolito** [larq/compute-engine#388]
Hello,

I've been having issues when trying to replicate the Quicknet benchmarks on Raspberry Pi. When I try to benchmark the Quicknet model, I get this error:

![image](https://user-images.githubusercontent.com/48355953/83322232-8511a700-a288-11ea-91e7-0e56f2c32303.png)

Initially, I was doing it on Raspbian Buster, but similar to #383, I got a very slow inference time (using the benchmarking tool, I got ~148 ms on 4 threads, and using the minimal code with some timing implemented, ~800 ms), so I also changed to Manjaro in order to improve inference time.

I built LCE directly, without the Docker container. When I was building LCE (using `larq_compute_engine/tflite/build_make/build_lce.sh --aarch64`), I got an error because of the way the AR variables were defined in the Makefile (both third_party/tensorflow/tensorflow/lite/tools/make/Makefile and larq_compute_engine/tflite/build_make/Makefile). So I changed it from `AR := $(CC_PREFIX)${TARGET_TOOLCHAIN_PREFIX}ar` to `AR := $(CC_PREFIX)${TARGET_TOOLCHAIN_PREFIX}gcc-ar`. After this, it seems to have finished building completely.

However, when I try to benchmark quicknet.tflite using the benchmark_model binary, I get the error above. When I try benchmarking other (non-binarized models such as Mobilenet_V2_1.0_224 and Mobilenet_V2_1.0_224_Quant from https://www.tensorflow.org/lite/guide/hosted_models), the benchmark_model works without issue.

This is how I converted your Quicknet h5 file to tflite:

![image](https://user-images.githubusercontent.com/48355953/83322365-9c04c900-a289-11ea-88b3-b04f809c52d7.png)

The resulting tflite model previously worked for me, since I was able to benchmark it before on Raspbian.

Here are the details of my set-up:

Device: Raspberry Pi 4 B (4 GB)
OS: Manjaro Raspberry Pi 4 Minimal (from /etc/lsb-release: DISTRIB_ID=Manjaro-ARM, DISTRIB_RELEASE=20.05)
Hash of my local compute-engine: 7202cc8 (HEAD -> master, origin/master, origin/HEAD) Support dilated convolutions in converter (#385)

**Comment by lgeiger** [comment]
Thanks for checking out larq compute engine.

We recently made some breaking changes in preparation for our next releases (mainly #373 and probably #386 soon as well).

This means `master` is currently not compatible with `.tflite` files generated with the 0.3.1 converter pip package. Once we move to a v1.0 release we will try to make sure we have proper op versioning so that issues like that are easier to debug.

For now I would recommend building your inference binary from the latest stable release [`v0.3.1`](https://github.com/larq/compute-engine/releases/tag/v0.3.1) which is ensured to be compatible with the converter published on PyPI.

Unless you require a specific unreleased feature I wouldn't recommend building the converter from master since it can take quite a long time to do so.

**Comment by kirstenhipolito** [comment]
Thanks for the update. 

I tried building from release v0.3.1 (cloned using `git clone -b 'v0.3.1' --single-branch https://github.com/larq/compute-engine.git`, then did the same as above. However I get this error during the build.

![image](https://user-images.githubusercontent.com/48355953/83328424-81484980-a2b5-11ea-93f9-b50712528713.png)

I do still get binaries built in _third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/_, but I think they're the ones from the initial tensorflow make. As expected, when I try using the binaries to benchmark quicknet, I get an error about unresolved custom ops.

![image](https://user-images.githubusercontent.com/48355953/83328493-ee5bdf00-a2b5-11ea-8316-6e73baf3af69.png)

I'll try to build the v0.3.0 release.

**Comment by lgeiger** [comment]
@kirstenhipolito did you check that you correctly checked out the git submodule in `third_party/tensorflow`?

You can make sure that it points to the right version by doing:
```
cd third_party/tensorflow
git checkout v2.2.0
cd ../..
```

I haven't used the make build myself, but cross compiling from x86 via the instructions [here](https://docs.larq.dev/compute-engine/build_arm/#cross-compiling-lce-with-bazel) should work correctly as well.

**Comment by kirstenhipolito** [comment]
I re-built compute-engine again following your instructions above, doing the make build, but I still got the same error.

Afterwards, I tried to also cross compile from ARM from x86 (within the Docker container, built the binaries using bazel), and it built successfully. However, when I copied the binaries to the Pi, and benchmarked quicknet_larq.tflite again, I got this error.

![image](https://user-images.githubusercontent.com/48355953/83335649-cdf54a00-a2e0-11ea-85db-cd6595cd1133.png)

If it helps, the quicknet_larq.tflite file that I'm using (converted from the published Quicknet h5 file) is this one: [https://github.com/kirstenhipolito/fast_od_rpi/blob/master/models_trained/quicknet_larq.tflite](https://github.com/kirstenhipolito/fast_od_rpi/blob/master/models_trained/quicknet_larq.tflite)

**Comment by lgeiger** [comment]
> I re-built compute-engine again following your instructions above, doing the make build, but I still got the same error.

Not sure what's going on with the make build there, did you run `larq_compute_engine/tflite/build_make/build_lce.sh --clean` before building the binary?

> If it helps, the quicknet_larq.tflite file that I'm using (converted from the published Quicknet h5 file) is this one

Which version of the larq compute engine pip package are you using to convert the model?
You can check this by running `pip freeze | grep larq-compute-engine`.

It should be `v0.3.1` in order to match your ARM binary, if not you can easily upgrade it using `pip install larq-compute-engine==0.3.1`.

**Comment by kirstenhipolito** [comment]
> Not sure what's going on with the make build there, did you run larq_compute_engine/tflite/build_make/build_lce.sh --clean before building the binary?

Yes initially I ran --clean before rebuilding, but got the error. To be sure, I deleted my local copy then just cloned again, but I still got the same error.

> It should be v0.3.1 in order to match your ARM binary, if not you can easily upgrade it using pip install larq-compute-engine==0.3.1.

It turns out this was the problem for me! I was using a v0.2.1 lce pip package, and when I updated it to v0.3.1 and re-converted the model, I was able to get 17.7 ms average inference time.

Would there be a resolution on the errors when natively compiling using make?

**Comment by lgeiger** [comment]
> It turns out this was the problem for me! I was using a v0.2.1 lce pip package, and when I updated it to v0.3.1 and re-converted the model, I was able to get 17.7 ms average inference time.

Glad you got it to work 🚀 

> Would there be a resolution on the errors when natively compiling using make?

I am not familiar with the make build, @Tombana do you know what could be going on here?

**Comment by kirstenhipolito** [comment]
Thanks for helping to resolve my issue! Since the replication problem has been addressed, I'll be closing this issue and opening a new issue for the error on natively compiling using make.
