### ISSUE TITLE
TF lite converter weight bitpacking

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#40]
Ideally we would like the TF lite converter to store the binary weights in a packed way so that the tflite model file stays small.

Another option might be that we write a tool ourselves that takes a converted `.tflite` model and does another pass on it, transforming the weights appropriately.

**Comment by arashb** [comment]
this is resolved in https://github.com/larq/compute-engine/commit/ef372f10cdb0edf6884c28cd873d2f3775470e2b
