### ISSUE TITLE
Floating point model runs even faster than Binarized model created by larq.

### ISSUE THREAD

**Issue by HuJiawei24** [larq/compute-engine#400]
I used Larq to create a binary resnet20 and a full precision resnet20 by setting the input quantiser and kernel quantiser to 'set_sign' and None respectively. I then converted the .h5 file into tflite files which are subsequently executed on raspberry pi4. The full precision model is even faster than the binary model, but the tflite file size looks correct as the full precision model file is much bigger than the binary model file. I also noticed that when I created the binary model with larq, the weight associated with the model is floating point instead of binary. Is this the latent weight used for training? it is also the weight when I save the model by model.save().

**Comment by HuJiawei24** [comment]
Hi, I’m sorry for the reply as I was extremely busy last week. The issue was solved when I used 64 bit os. Thank all of you for your kind help!!

**Comment by lgeiger** [comment]
Glad you got it working 👍
