### ISSUE TITLE
Improve build instructions

### ISSUE THREAD

**Issue by lgeiger** [larq/compute-engine#409]
Our [build instruction](https://docs.larq.dev/compute-engine/build/) currently recommend to clone the repo from master when building. This has caused some confusion since models converted with the stable pip package might not be compatible with the the runtime built from master (E.g. #408, #388, and [spectrum comment](https://spectrum.chat/larq/compute-engine/encountered-unresolved-custom-op-resizenearestneighbor~ca8059dd-628e-40ed-8d3a-04894a8f0e64?m=MTU4OTg1NDY2Njk5Mw==)).

We should change the build instructions to recommend pulling the latest stable release tag and should simplify the cross-compilation instructions to recommend using the [published docker image for v0.3.1](https://github.com/larq/compute-engine/packages/256695) which already includes all required dependencies and the correct version of the code.

**Comment by honglh** [comment]
from build instructions [https://docs.larq.dev/compute-engine/build_arm/](here)

**Comment by Tombana** [comment]
Thanks @honglh, we'll add that to the build instructions!

**Comment by Tombana** [comment]
Note to self: the build instructions for the converter have to be updated. By default they build for the wrong python version, see https://github.com/larq/compute-engine/issues/408.

**Comment by lgeiger** [comment]
> Note to self: the build instructions for the converter have to be updated. By default they build for the wrong python version, see https://github.com/larq/compute-engine/issues/408.

Good point.
I think it might also be useful to add a big note that recommends using the stable converter from pypi if possible since building it from source can be a bit of a pain.

**Comment by jneeven** [comment]
The build instructions could also use some description of how to get bazelisk on MacOS, they currently only specify what to do for linux:
```
sudo wget -O /usr/local/bin/bazel \
    https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-linux-amd64
sudo chmod +x /usr/local/bin/bazel
```
(@leonoverweel )

**Comment by leonoverweel** [comment]
Yeah just running `brew install bazel` did not work:

```
ERROR: The project you're trying to build requires Bazel 3.0.0 (specified in /Users/leon/Repositories/Plumerai/vww-demo/lce-micro/.bazelversion), but it wasn't found in /usr/local/Cellar/bazel/3.2.0/libexec/bin.
```

**Comment by AdamHillier** [comment]
You can `brew install bazelisk` I believe. And if not, you can install [through npm](https://docs.bazel.build/versions/master/install-bazelisk.html).

**Comment by AdamHillier** [comment]
(Personally, I install bazelisk through brew, and then symlink `/usr/local/bin/bazel -> /usr/local/bin/bazelisk`.)

**Comment by leonoverweel** [comment]
> (Personally, I install bazelisk through brew, and then symlink `/usr/local/bin/bazel` -> `/usr/local/bin/bazelisk`.)

Nice, this seems to have worked for me.

**Comment by Tombana** [comment]
Note to self: make sure that the bug in #411 does not occur when the build instructions are updated.

**Comment by lgeiger** [comment]
Note to self: I think it makes sense to also have docs for a "development" setup which goes into detail on how to run the tests and install LCE from master.

**Comment by Tombana** [comment]
Here I'm collecting the build issues that people have run into, with a green circle if they've been fixed.

- :red_circle: In general, people had trouble with mismatching compiler/runtime versions (https://github.com/larq/compute-engine/issues/408 but I think also other users). The docs should reflect this version-matching more clearly.

- :green_circle:  https://github.com/larq/compute-engine/issues/411  compiling the pip package in the Docker container without any setup --> fixed by updating docs to tell users to build outside of docker or to use the `release_linux.sh` script inside Docker
- Issue https://github.com/larq/compute-engine/issues/396
    - :orange_circle: `ar` command not found. We've not been able to reproduce this issue, but the user fixed it themselves by using `gcc-ar` instead.
    - :green_circle: broken path to `libtensorflow-lite.a` . Was fixed by a tensorflow commit, see also https://github.com/larq/compute-engine/pull/480
- Issue https://github.com/larq/compute-engine/issues/408
    - Mismatching converter/runtime versions, already listed above.
    - :green_circle: Building the converter for particular python versions --> docs have been updated to explain this
    - :green_circle: broken path to `libtensorflow-lite.a` is now fixed, see above

**Comment by lgeiger** [comment]
Closed via https://github.com/larq/docs/pull/124
