### ISSUE TITLE
lce_minal error

### ISSUE THREAD

**Issue by dddf-fly** [larq/compute-engine#410]
I use larq_compute_engine  convert V0.3.1 in the pip repository.
The lce runtime I build is V0.3 too,but I got ERROR :Encounter unresolved custom op:Mul.
ERROR: Node number 11(Mul) failed to prepare.

**Comment by Tombana** [comment]
Hi, thanks for trying out LCE!
Could you open your converted `.tflite` file with [netron](https://lutzroeder.github.io/netron/) and post a screenshot of that? (or send the `.tflite` file itself if that is easier)

**Comment by lgeiger** [comment]
@Tombana This seems to be related to [this issue](https://spectrum.chat/larq/compute-engine/encoutered-unresolved-custom-op-mul~5fc8c71b-c1dd-4c0e-b57c-2b27761a8d3b) since LCE currently doesn't have support for binarized dense layers.

**Comment by dddf-fly** [comment]
Yes,It is related to the issue(https://spectrum.chat/larq/compute-engine/encoutered-unresolved-custom-op-mul~5fc8c71b-c1dd-4c0e-b57c-2b27761a8d3b). the .tflite I'm using is your mnist example on your website, and I converted it by lce.convert_keras_model. Does it means that I can not use BatchNormalization layer after QuantDense layer?
![批注 2020-06-24 095934](https://user-images.githubusercontent.com/65340203/85488761-6db4a800-b601-11ea-98cb-be9c092b6c45.png)

**Comment by dddf-fly** [comment]
I use the larq.models.summary(model) to show the model. I got the following output. What dose the "?" in the column "1bit-MACS" and "32-bit MACS" mean?
![批注 2020-06-24 104512](https://user-images.githubusercontent.com/65340203/85492472-cd15b680-b607-11ea-93ce-308c16d6f750.png)

**Comment by Tombana** [comment]
> Yes,It is related to the issue(https://spectrum.chat/larq/compute-engine/encoutered-unresolved-custom-op-mul~5fc8c71b-c1dd-4c0e-b57c-2b27761a8d3b). the .tflite I'm using is your mnist example on your website, and I converted it by lce.convert_keras_model. Does it means that I can not use BatchNormalization layer after QuantDense layer?

Thank for the clarification.
Currently we don't support binary fully-connected layers in LCE (only binary convolutions). That means the converter will leave them as `float32` or `int8` layers, so they can be executed by tflite, but they will not be as fast as a binary layer could be.

However in version `v0.3.1` of the converter, constant-folding is not yet implemented, and that means a BatchNormalization after a QuantDense layer will not work. This will likely be fixed in the next version of our converter, then you should be able to run this example again. However, we will then still not support binary fully-connected layers, so they will stay as `float` or `int8`. Therefore, until we implement binary dense layers in LCE, a better solution is to use a normal Dense layer instead of making it binary because the speed in LCE would be the same anyway.

**Comment by dddf-fly** [comment]
Thank you very much for your detailed explanation.

**Comment by koenhelwegen** [comment]
> What dose the "?" in the column "1bit-MACS" and "32-bit MACS" mean?

This means MAC counts for these layers is not supported. The layers for which the MAC count is supported are listed [here](https://github.com/larq/larq/blob/04ea8153ef10484dab68873cfe3ea37db5615ca4/larq/models.py#L14) - for any other layer we print question marks (these are ignored when calculating the total). Beware that by MACs we strictly mean multiply-accumulate ops such as appear in convolutions and fully connected layers. Element-wise operations such as batchnorm or relu are considered to have 0 MACs.

**Comment by dddf-fly** [comment]
Thank you very much for your detailed explanation. I still have one more question. What does "32-bit MACS" mean? Does it include multiply–accumulate operation for both  32-bit integers and 32-bit float numbers?

**Comment by koenhelwegen** [comment]
To determine the bit width of the operation we look at the precision attribute of the quantizers on input weights & activations and take the maximum. If no quantizer is found, we default to 32. So anything without Larq quantizers will show up as 32, incl `tf.int32` and `tf.float32` (but also `tf.float16`, `tf.float64` etcetera - the summary is intended to get an overall idea of the network, for more detailed information I recommend inspecting the converted `.tflite` files).

**Comment by dddf-fly** [comment]
Thank you very much for your detailed explanation.
