### ISSUE TITLE
Broken links to LCE converter page

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#412]
Some links on https://docs.larq.dev/compute-engine/ (and maybe elsewhere) are pointing to https://docs.larq.dev/compute-engine/converter/ (but it should probably be https://docs.larq.dev/compute-engine/api/converter/).

**Comment by koenhelwegen** [comment]
Thanks for flagging this! #413 will fix this on master, in principle the website is synced with the next release.
