### ISSUE TITLE
Output tensor is used by LceBconv2d in toy_model_int8

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#423]
I'm experimenting with the following toy model from `end2end_test.py`:

```
import larq as lq
import larq_compute_engine as lce

def quant(x):
    return tf.quantization.fake_quant_with_min_max_vars(x, -3.0, 3.0)

def toy_model_int8(**kwargs):
    img = tf.keras.layers.Input(shape=(224, 224, 3))
    x = quant(img)
    x = lq.layers.QuantConv2D(
        12, 3, input_quantizer="ste_sign", kernel_quantizer="ste_sign", activation=quant
    )(x)
    x = lq.layers.QuantConv2D(
        12, 3, input_quantizer="ste_sign", kernel_quantizer="ste_sign", activation=quant
    )(x)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = lq.layers.QuantDense(
        10, input_quantizer=quant, kernel_quantizer=quant, activation=quant
    )(x)
    x = tf.keras.layers.Activation("softmax")(x)
    return tf.keras.Model(img, x)

model = toy_model_int8
model_lce = lce.convert_keras_model(
    model, experimental_enable_bitpacked_activations=True
)

with open("model_larq_int8.tflite", "wb") as f:
    f.write(model_lce)
```

The output model and a visualization are attached here: [model_larq_int8.zip](https://github.com/larq/compute-engine/files/4881109/model_larq_int8.zip)

Strangely, tensor 14 is not only the output of the model, but also an input to the two binary ops as well. I'm not sure how to run the tests for the LCE, but wouldn't this cause some issues when the model is run repeatedly?

**Comment by lgeiger** [comment]
I am not sure if I understand the visualization you linked correctly. I haven't manually inspected the flatbuffer, but if I open the model in [netron](https://github.com/lutzroeder/netron) it correctly shows only four inputs to the BConv and no usage of Tensor 14, whereas your visualization tool shows five:
<img width="909" alt="Screenshot 2020-07-06 at 22 52 56" src="https://user-images.githubusercontent.com/13285808/86642308-17ba0a00-bfdc-11ea-9dfa-bb5cd57632e5.png">

> I'm not sure how to run the tests for the LCE

You can run the end2end tests using `bazelisk test larq_compute_engine/tests:end2end_test --test_output=all --copt=-O2`, though CI seems to be happy with it.

**Comment by lkindrat-xmos** [comment]
Thanks for looking into this, I looked at the flatbuffer, and it seems that my visualizer was interpreting the -1 input index (i.e. optional) incorrectly as the last one in the tensor list.

**Comment by lgeiger** [comment]
:+1:

On a different note, if you want to make use of `experimental_enable_bitpacked_activations=True` I'd recommend to remove `activation=quant` from the first BConv so that the two BConvs can correctly read and write bitpacked output.
