### ISSUE TITLE
Question about binary Deconv

### ISSUE THREAD

**Issue by achigeor** [larq/compute-engine#424]
Hi,

First of all thank you for the great library! Very easy to use and integrate into existing TF training pipelines! :+1: 

I have a question regarding `QuantConv2DTranspose`. I run some simple benchmarks and it seems that there is no difference in speed between binary and real. Actually, it seems that the real variant is a tad faster too:
*  Inference: 8312.83 for a single binary deconv layer
*  Inference: 8043.37 for a single real deconv layer (everything the same as binary)

Also, checking the graph it seems that the only difference between the two is the `LceBsign` op before the deconv op as seen in the pictures below. 

Is this expected behaviour or am I missing something? Thank you!

Real:
![image](https://user-images.githubusercontent.com/6160474/86824389-60ca9680-c08e-11ea-98da-8c57e18fd06c.png)

Binary:
![image](https://user-images.githubusercontent.com/6160474/86824346-527c7a80-c08e-11ea-9fbf-2ddafcffa19a.png)

**Comment by Tombana** [comment]
> Very easy to use and integrate into existing TF training pipelines!

Thanks!

We currently have no optimized binary transpose convolution, so it will fallback to the non-binary one and it uses `LceBsign` to make sure the inputs are in `{-1, +1}`. The extra `LceBsign` is the reason that its just slightly slower than the non-binary case. This is expected behaviour.

**Comment by achigeor** [comment]
Thanks for the quick response and explanation @Tombana! 

Some followups:
* Is there a list of the optimized binary operations somewhere? 
* Is there a [public] roadmap for the optimization of non-optimized ops? 
* Would it be safe to just use the non-binary transpose conv in combination with binary ops, or is this a matter of experimentation / network specific?

**Comment by lgeiger** [comment]
> Is there a list of the optimized binary operations somewhere?

We [will have a list of supported binary operations (only bconv2d and maxpool)](https://nightly.docs.larq.dev/compute-engine/api/operators/#lcebconv2d) in the docs for the upcoming 0.4 release.

> Is there a [public] roadmap for the optimization of non-optimized ops?

Currently we don't plan to add more ops in the near future as we are mostly working on improving the process with our current set of ops (e.g. compatibility with int8 and some refactors to stabilize the op definition). Howver, I'd be very interested in learning more about your use case and we would be happy to accept contributions and offer help if you are interested in adding support for optimized binarized transposed convolutions to Larq Compute Engine.

> Would it be safe to just use the non-binary transpose conv in combination with binary ops

I think this would be the recommended workflow.
It looks like the model you posted didn't correctly constant fold the weights of the transposed convolution, I tested with the latest master which is built ontop of TF 2.3 and a full precision transposed convolution converts to:
![Screenshot 2020-07-08 at 15 48 16](https://user-images.githubusercontent.com/13285808/86926754-bb1d3300-c132-11ea-9c98-461e575d0931.png)
I didn't measure, but I would expect that this might significantly improve performance of the full precision op in the next release of Larq Compute Engine.

**Comment by achigeor** [comment]
Thanks for the clarifications and links @lgeiger!

> Currently we don't plan to add more ops in the near future as we are mostly working on improving the process with our current set of ops (e.g. compatibility with int8 and some refactors to stabilize the op definition). Howver, I'd be very interested in learning more about your use case and we would be happy to accept contributions and offer help if you are interested in adding support for optimized binarized transposed convolutions to Larq Compute Engine.

The current focus makes a lot of sense. Would be great if there's a public roadmap indeed, helps a lot to understand the progress as well as limitations.
* Regarding my usecase: I'm currently more of exploring the world of BNNs for vision - reading papers and training basic networks. So I was playing around with different layers and architectures to understand limitations. 
* Regarding contributions: It would be great if you can give some pointers as to where to look for the current optimized version of Conv2D or how to start in general. Unfortunately I can't commit though due to my current schedule, but I'd love to play around and see if I can contribute :) 

> It looks like the model you posted didn't correctly constant fold the weights of the transposed convolution, I tested with the latest master which is built ontop of TF 2.3 and a full precision transposed convolution converts to:

Indeed! Is there an ETA on the next release? Or how can I try it now? Should I just install LCE from master and convert my current model?

Thanks!

**Comment by lgeiger** [comment]
> Regarding contributions: It would be great if you can give some pointers as to where to look for the current optimized version of Conv2D or how to start in general. Unfortunately I can't commit though due to my current schedule, but I'd love to play around and see if I can contribute :)

For adding new ops #365 is probably the best place to start. The optimized implementation of our BConv2D for AArch64 can be found [here](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/core/bgemm_kernels_arm64.h) in order to use the op in an actual model support in the converter would need to be added as well which converts the [TF ops to the relevant optimized binarized ops](https://github.com/larq/compute-engine/blob/0bb5ead31c2aedb55c4b6ad8c02a306fbb860ba2/larq_compute_engine/mlir/transforms/prepare_patterns.td#L43-L71).

> Is there an ETA on the next release?

We currently don't have an excact ETA, but we will definitely await the TF 2.3 stable release before the next version.
