### ISSUE TITLE
BgemmKernel for ARM32

### ISSUE THREAD

**Issue by honglh** [larq/compute-engine#431]

**Comment by honglh** [comment]
Hi,

Based from [BgemmKernel 64](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/core/bgemm_kernels_arm64.h)  and [Ruy](https://github.com/google/ruy/blob/master/ruy/kernel_arm32.cc) I have implemented the 32 bit BgemmKernel.  I have tested on RPI2 32bit, RPI3 32-bit and they have comparable performance against RPI3 64-bit, though I have not run full benchmark.

Please check out the [PR 432](https://github.com/larq/compute-engine/pull/432) for the changes I made, mostly in the new file `bgemm_kernels_arm32.h`   This is a specific implementation for kernel layout 4x4

Most of my development and testing are done with `v0.3.1` When I try to use `master` I still run into issue #408  thus I cannot  test on `master` even though my PR Is based from `master`

Overall I think this would be helpful for users of  ARM devices where 32 bit is the only option e.g. RPI2

**Comment by honglh** [comment]
I can see a couple CI/CD builds failed on github.  Not sure how to run the tests offline. Please let me know if you have more details of the error or some instructions I can test the build offline in my local setup.  Thanks!

**Comment by lgeiger** [comment]
Thank you very much for contributing and sorry for the missing instructions on how to properly setup a dev environment we'll try to add a proper guides soon. For now I hope the following will get you started:

> Most of my development and testing are done with v0.3.1 When I try to use master I still run into issue #408 thus I cannot test on master even though my PR Is based from master

Please checkout and let me know if that works for you https://github.com/larq/compute-engine/issues/408#issuecomment-662323177

**Comment by lgeiger** [comment]
Closed via #432
