### ISSUE TITLE
Preprocessed outputtransform

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#450]
We can include the `1.0 / output_scale` multiplication into the `post_activation_multiplier`, and we can reorder the `clamp` (activation function) and the backtransform:

Old:
- backtransform `n - 2 * x`
- clamp
- `x * multiplier[channel] + bias[channel]`
- divide by int8-scale, add int8 zero-point
- int8-saturate

New:
- multiply by 2 (bitshift) `2 * x`
- clamp
- `x * multiplier[channel] + bias[channel]` now including int8 scale and zero-point
- int8-saturate

Note: you could even merge the clamp and int8-saturate but they would become channel-dependent, and now they are channel-independent.

For the float output kernels (including the assembly kernels) we would still merge the backtransform and post_activation transformation.

**Comment by lgeiger** [comment]
After discussing this offline, we decide not to do this preprocessing already in the flatbuffer converter as this would expose too many implementation details.

Closing this issue for now, as this optimization can be done in the kernel `Prepare` step or a custom target specific flabuffer transformer.
