### ISSUE TITLE
LceBconv2d "padding" custom option enum

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#458]
It looks like the `padding` custom option is encoded as a `TfLitePadding` enum value. While there is nothing that prevents using this in a custom option, it is slightly odd since the built-in TFL operators all use the `Padding` enum from the schema. The difference is that `TfLitePadding` can encode unknown padding, which is not permitted by the schema (only same and valid).

If there is no need for the custom options to encode the unknown case, would it be possible to change this? It seems desirable to make the serialized flatbuffer depend explicitly on the runtime as little as possible, and would also make our code simpler.

**Comment by lgeiger** [comment]
> If there is no need for the custom options to encode the unknown case, would it be possible to change this?

I am not sure if I correctly understand your question, could you elaborate a bit more? The bconv op is a TFLite custom op which only allows for custom options using flexbuffers.

TFLite builtin ops work a bit differently and have [operator options defined in the flatbuffer schema](https://github.com/tensorflow/tensorflow/blob/6bcd7a22d588d48c2faa7ea495350b0cb5f32ba0/tensorflow/lite/schema/schema_v3.fbs#L132-L148) which handle deserialization and [converts them to the runtime type used by the kernels](https://github.com/tensorflow/tensorflow/blob/e9bf0700e5aea3b368a11abfb1bbe105381f18c3/tensorflow/lite/core/api/flatbuffer_conversions.cc#L104-L132).

If I understand it correctly moving away from custom ops and options would require us to modify the flatbuffer schema which would break the compatibility of our ops with the default TFLite and TFLite micro runtime. As far as I can tell this would require us to fork the entire TFLite runtime to add our op.
While we could switch from using `TfLitePadding` to `Padding` and from `TfLiteFusedActivation` to `ActivationFunctionType` in the custom options, we would still need to convert it somehow before using it in the kernels, or am I missing something?

**Comment by lkindrat-xmos** [comment]
I am not at all suggesting moving away from custom options.

> While I'd be open to switch from using `TfLitePadding` to `Padding` and from `TfLiteFusedActivation` to `ActivationFunctionType` in the custom options we would still need to convert it somehow before using it in the kernels, or am I missing something?

This is precisely what I meant. There are existing functions for conversion here that the TFL runtime uses: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/api/flatbuffer_conversions.cc#L124

`TfLitePadding` to me looks like an implementation detail of the TFL runtime and I think it is a good idea to use it in the LCE runtime as well (although nothing prevents you from not doing that, e.g. by using your own enum, or `Padding` from the schema, and then you could avoid the conversion too). However, using it when serializing your flatbuffer seems unintuitive, since you end up depending on the implementation of the TFL runtime, rather than the schema (whose purpose is to govern serialization).

Does this clarify the issue?

**Comment by AdamHillier** [comment]
> I don't have a strong opinion on that and since 0.4 will be a breaking release anyway I don't think changing the enum would be too problematic. @AdamHillier @Tombana What do you think?

I also have no strong feelings about this at all, I'm fine with changing it.

**Comment by Tombana** [comment]
> However, using it when serializing your flatbuffer seems unintuitive, since you end up depending on the implementation of the TFL runtime, rather than the schema (whose purpose is to govern serialization).

This makes a lot of sense, I'm fine with changing it to `Padding`.

I think when we implemented this, I originally picked `TfLitePadding` because '`Padding` -> `TfLitePadding`' just seemed like an extra conversion step that the runtime would have to do, so why not cut it out to make the code simpler. @lkindrat-xmos's argument is much better, so lets change it to `Padding`.

**Comment by lgeiger** [comment]
Sounds great! We can do this after #461 and #457 have been merged to prevent unnecessary merge conflicts.

**Comment by lkindrat-xmos** [comment]
Thanks guys, we appreciate it!
