### ISSUE TITLE
Unused buffers

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#548]
As I continue to hack my way around the LCE, I noticed that the flatbuffer models have some unreferenced buffer objects in them. The code below produces a model where buffers with indices `[0, 1, 8]` are not referenced by any tensors or metadata. What are these used for? If I remove these buffers manually, the `lce.tflite.python.interpreter.Interpreter` segfaults (but there is a chance that's just because I messed up something while I was performing surgery on the flatbuffer).

```
import tensorflow as tf
import numpy as np
import larq as lq
import larq_compute_engine as lce

def quant(x: tf.Tensor) -> tf.Tensor:
    return tf.quantization.fake_quant_with_min_max_vars(
        x, -3, 3
    )

def mymodel():
    img = tf.keras.layers.Input(shape=(8, 8, 32))
    x = quant(img)
    x = lq.layers.QuantConv2D(
        filters=32,
        kernel_size=3,
        strides=2,
        padding="same",
        pad_values=1,
        input_quantizer="ste_sign",
        kernel_quantizer="ste_sign",
        kernel_constraint="weight_clip",
    )(x)
    x = quant(x)
    return tf.keras.Model(img, x)

model_w_buffers = lce.convert_keras_model(
    mymodel(),
    inference_input_type=tf.int8,
    inference_output_type=tf.int8,
)

interpreter = lce.tflite.python.interpreter.Interpreter(model_w_buffers)
input_data = np.zeros(interpreter.input_shapes[0], dtype=interpreter.input_types[0])
output_data = interpreter.predict(input_data)

with open("model_w_buffers.tflite", "wb") as f:
    f.write(model_w_buffers)
```

Here is the model generated by the code above, as well as the one with the unreferenced buffers removed:
[larq_model_buffers.zip](https://github.com/larq/compute-engine/files/5425524/larq_model_buffers.zip)

**Comment by Tombana** [comment]
That's interesting, thanks for raising this. I can indeed confirm that the model you sent seems to have unreferenced buffers. So far we've never had to look at the flatbuffers in this much detail; usually the info shown by netron was sufficient. I'll look into it.

**Comment by Tombana** [comment]
I've found the following line in the "mlir-to-flatbuffer" exporter, which says that an empty buffer at index `0` is apparently part of the schema definition:
https://github.com/tensorflow/tensorflow/blob/5bbb8a2bd1def6865b1510175a3da5fd12387e10/tensorflow/compiler/mlir/lite/flatbuffer_export.cc#L365-L366

As for the other two unrefrenced buffers: I've noticed that the same happens with a normal Conv2D, and also when using the normal (non-lce) tensorflow converter.

When using the extra quantize/dequantize ops at the start (by having `inference_input_type=tf.float`), all buffers except `0` are referenced. Buffers `1` and `6` (in my local int8 conv example) were referenced by the input and output tensors of the model (before the Quantize op and after the Dequantize op). By enabling the int8 input/output types, these ops dissapear, but somehow buffers `1` and `6` remain in the flatbuffer. This might be a bug in the tensorflow MLIR converter, I'm not sure.

**Comment by lkindrat-xmos** [comment]
Great, thanks for investigating! I did notice that if I retain only one empty buffer in the beginning, the interpreter works as expected, this explains that. Indeed, the schema mentions that buffer 0 is used by Tensors that don't reference a buffer:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs#L192
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs#L1130
This seems inconsistent with how operators designate optional inputs/outputs, but it makes sense since the buffer index is `uint` (maybe a poor choice in retrospect), while inputs and outputs are `[int]`.

An interesting tidbit:
Our optimizer removes all empty buffers (including the first one), and we have never run into this issue before. We run models on our port of the micro interpreter, which just works fine without a sentinel buffer. I also created a flatbuffer with just a single `LceQuantize` and the input/output tensors (no sentinel buffer), and the LCE interpreter works. Can you see any reason why `LceBconv2d` might reference buffer 0? Maybe the way the optional inputs are handled?

Anyway, feel free to close this issue. (BTW, should we report this to the TF people?)

**Comment by Tombana** [comment]
> Our optimizer removes all empty buffers (including the first one), and we have never run into this issue before. 

Interesting. The micro interpreter has its own code for parsing the flatbuffer and handling allocations, separate from the tflite (non-micro) version. Since the lce python interpreter uses the non-micro version, that might also explain these differences.

> Can you see any reason why `LceBconv2d` might reference buffer 0? Maybe the way the optional inputs are handled?

I have no idea, optional inputs do indeed sound like good candidates.

> BTW, should we report this to the TF people?

I think so yes, I'll prepare a minimal example next week and report it.

**Comment by Tombana** [comment]
Update: I found the culprit. In https://github.com/tensorflow/tensorflow/commit/ec94fabb838b0934eeaf46f1fd22c36b2b3ec333 (only in `tf-nightly` at the moment) TF added support for setting the input/output types to `int8` and eliminate the Quantize/Dequantize pair. They do that [in this function](https://github.com/tensorflow/tensorflow/blob/b0784e587b62eec6967196b745bba4db3a90ab0c/tensorflow/lite/python/util.py#L632), which we use in LCE [over here](https://github.com/larq/compute-engine/blob/ca8ea85e8837cd4249eee78768f9865bf86bd03e/larq_compute_engine/mlir/python/util.py#L168). This function does cleanup unreferenced *tensors* [over here](https://github.com/tensorflow/tensorflow/blob/b0784e587b62eec6967196b745bba4db3a90ab0c/tensorflow/lite/python/util.py#L710) but they don't cleanup unreferenced *buffers*.

TF issue is here https://github.com/tensorflow/tensorflow/issues/44353 .
