### ISSUE TITLE
larq-compute-engine installing issue 

### ISSUE THREAD

**Issue by FrancescoLoro** [larq/compute-engine#553]
Hi, I used larq to create a BNN from a full precision network to make some comparisons. 
I would like to install your lce library on a raspberry pi 4 model B. 
However, by running the command "pip install larq-compute-engine, as suggested in the end to end guide, I get this error:
ERROR: Could not find a version that satisfies the requirement larq-compute-engine (from version: none)
Do you, please, have any idea about how i can fix this? 
Regards.

**Comment by jneeven** [comment]
Hi, nice to see you're interested in BNNs and the Larq ecosystem! Which python version are you trying to install LCE for? We support python versions 3.6 and above. It seems your python package manager can't find any LCE versions, which indicates that you're probably on an unsupported python version, or your pip is a bit outdated. Could you tell me the output of the `pip --version` command?

If pip is indeed the problem, you should be able to fix it by running `python -m pip install --upgrade pip` (assuming that `python` refers to python version >= 3.6 on your system). Let me know if that works for you!

**Comment by FrancescoLoro** [comment]
Hello, thanks for the quick response.
I'm using python 3.7.3 and pip 20.2.4

**Comment by jneeven** [comment]
> Hello, thanks for the quick response.
> I'm using python 3.7.3 and pip 20.2.4

Okay, in theory that should be absolutely fine, but now that I've re-read your original message I see you're trying to install LCE on the Raspberry Pi itself. The LCE converter currently only supports x86 architectures (you can see the list of wheels [here](https://pypi.org/project/larq-compute-engine/#files)), but the Raspberry Pi uses ARMv8. 
We therefore recommend that you install the converter on another device instead (such as your laptop), and convert the model from there. The actual inference engine can of course still be run on (and is optimized for) ARMv8. Hope that helps!

**Comment by FrancescoLoro** [comment]
Ok so i should create and train my model, convert it with LCE on my laptop. And then load the already converted model on the raspberry and run the inference with normal larq library?

**Comment by jneeven** [comment]
> Ok so i should create and train my model, convert it with LCE on my laptop. And then load the already converted model on the raspberry and run the inference with normal larq library?

Yes, correct! But you wouldn't use Larq for inference, as it's only a training library. That's where the Larq Compute Engine comes in: to benchmark your converted model on your Raspberry Pi, you can follow the [benchmarking part of the end-to-end guide](https://docs.larq.dev/compute-engine/end_to_end/#benchmarking), which simply downloads a pre-built benchmarking binary that you can pass your converted model to. 

If you want to actually use your model for inference in an application of some kind (i.e. if you care about the inputs and the predictions), check out our [C++](https://docs.larq.dev/compute-engine/inference/) or [Android](https://docs.larq.dev/compute-engine/quickstart_android/) inference guides.

**Comment by FrancescoLoro** [comment]
Exactly, my purpose is to test the performance of my BNN on the raspberry pi 4 device. And this involves running the inference directly on the raspberry. I will try to follow the guide for C++ to use my network on the raspberry.

**Comment by jneeven** [comment]
Okay, good luck! If you experience any problems there, feel free to open another issue :+1:

**Comment by FrancescoLoro** [comment]
Thank you very much for your help

**Comment by godhj93** [comment]
Hi, all.

Is there any way to use python API like ```interpreter.predict(x)``` in raspberry PI?

basically tensorflow lite supports python API in [here](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) so i want to know whether i can use python function for larq inferencing

**Comment by godhj93** [comment]
Hi, all 

is there any way to use python API like ```interpreter.predict(x)``` ?

I want to know whether i can use python function for inferencing in larq like tensorflow lite [here](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python)

**Comment by Tombana** [comment]
> is there any way to use python API like `interpreter.predict(x)` ?
> 
> I want to know whether i can use python function for inferencing in larq like tensorflow lite [here](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python)

There is a Python interpreter, but it is not optimized for speed so it can not be used for benchmarking latency: https://docs.larq.dev/compute-engine/api/python/#interpreter

**Comment by chartain02** [comment]
Hello everyone.... I am trying to do the inference using larq compute engine and i want to use the c++ script as shown in lce_minimal.cc but i am finding my self in trouble due to nan error....can someone provide a script where we have code for input and output as well? I would highly appreciate if you can provide me with the example for imagenet dataset. @Tombana @jneeven
