### ISSUE TITLE
What is the difference between LCE and ARM NN?

### ISSUE THREAD

**Issue by ivs-pychen** [larq/compute-engine#554]
Which tool(LCE or ARM NN) can be used to deploy the BNN model trained by larq on ARM CPU, GPU, NPU? 

And what is the difference between LCE and ARM NN?

**Comment by Tombana** [comment]
As far as I know, ARM NN does not support binary (i.e. 1-bit quantized) layers. So if you've trained a model with binary layers using Larq, then you should deploy it with LCE.

**Comment by ivs-pychen** [comment]
Ok. Thank you.
