### ISSUE TITLE
LCE works great on ARM but is slow on x86_64

### ISSUE THREAD

**Issue by bferrarini** [larq/compute-engine#591]
Hi,

I wrote my first application for the RPI4. The inference speed is awesome.

I need to collect comparative data from a regular workstation for an academic purpose, but I found that the inference is by far slower on x86_64 machines.

To check whether I missed something in my software, I compiled the lce_benchmark on a Linux box equipped with a 64bit processor (--native flag) using the Docker method.
The benchmark confirms that the inference time on my i7-7700K is something like 8-12 times slower than RPI4's ARM.

Is that the expected behaviour (target platform, optimization, etc.) or is there a building method specific for x86 platforms?

Kind Regards,

Bruno

**Comment by AdamHillier** [comment]
Hi Bruno,

Thanks for your interest in LCE! I'm afraid that this behaviour is expected. LCE specifically targets ARM v8-a devices (like your RPi), and the BNN kernels that accelerate binary convolutions are written in ARM assembly to be as fast as possible on those platforms. On x86 we don't have optimised assembly kernels and so any binary built for an x86 target will use slow C++ reference kernels instead.

Unfortunately improved x86 support is not on our roadmap for the time being, but we always welcome external contributions if there's anybody who wants to work on optimised x86 kernels :)

For your academic comparison purposes, the only alternative I can suggest is using an ARM benchmark binary running with QEMU on your workstation. It's very much not ideal, but it *might* perform better than the native x86 binary.

**Comment by bferrarini** [comment]
Hi Adam,

Many Thanks for your super quick reply :)

The actual target of my application is ARM indeed.
I will make a try with QEMU just to have an idea of the performance gap. 

Regards, 
Bruno
