### ISSUE TITLE
lce_converter build from source error: /tmp/lce_android

### ISSUE THREAD

**Issue by simonmaurer** [larq/compute-engine#598]
Hi all

I was trying to build the Larq Compute engine in a virtual environment using Python3.7/TensorFlow2.4.1.
Given the instructions [https://docs.larq.dev/compute-engine/build/converter/](https://docs.larq.dev/compute-engine/build/converter/) and after executing
`bazel clean --expunge`
`bazel build :build_pip_pkg`

I get the following error:

> (tf2.4) ➜  compute-engine git:(bazel3.7.0) ✗ bazel build :build_pip_pkg
Starting local Bazel server and connecting to it...
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: The repository's path is "/tmp/lce_android" (absolute: "/tmp/lce_android") but a symlink could not be created for it, because: /tmp/lce_android (No such file or directory)
INFO: Elapsed time: 13,699s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 27 targets configured)
    currently loading: larq_compute_engine/mlir ... (3 packages)
    Fetching @local_config_cuda; fetching
    Fetching @local_execution_config_python; fetching
    Fetching @local_config_sh; fetching
    Fetching @local_config_cc_toolchains; Restarting.
    Fetching @rules_java; fetching

Trying to solve using [Android NDK install script](https://docs.larq.dev/compute-engine/build/android/) worked out, just asking myself why this would be needed as the compilation for the converter is native for the host platform (macOS, Intel i5-8259U in this case) ?
Running the install script in a docker container makes sense, for a build on a host machine is there an alternative other than changing the install path in the script to something else than /tmp/lce_android ?

**Comment by simonmaurer** [comment]
Hi @AdamHillier 
I really have to say it is great work y'all did and I'm using it for research purposes.
 Already talked to @lgeiger via mail about some specific questions, but I'm working on posting these as different issues ;)

Regarding your feedback:
1. building from latest master branch [https://github.com/larq/compute-engine/commit/579c8fb02f69d6f08e1581206c7b9b00b5394028](url)
2. did that yes. specifying Python install paths (in virtual environment) and optimization flags
3. yes, it went through building it (still compiling in this moment). just wondering why this step is needed as I'm only building the converter not the inference engine for Android for example

**Comment by AdamHillier** [comment]
Hmm, that is very weird. I just did the following, also on MacOS, with a completely fresh LCE repo and Python environment:

```
git clone git@github.com:larq/compute-engine.git tmp-lce
cd tmp-lce
python3 -m venv env
source env/bin/activate.fish
pip install tensorflow
python configure.py
bazel build :build_pip_pkg
```

and after downloading the dependencies the Bazel analysis succeeded, and it started compiling files.

> ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: The repository's path is "/tmp/lce_android" (absolute: "/tmp/lce_android") but a symlink could not be created for it, because: /tmp/lce_android (No such file or directory)

I really don't have any idea what could have caused this for you; that Bazel build target shouldn't be triggering anything Android related.

Any thoughts @lgeiger?

**Comment by simonmaurer** [comment]
thanks for trying to reproduce. it really is weird.
just as additional hint, not sure if this is the cause though : I'm using `bazel 3.7.0-homebrew` and modified the .bazelversion to `3.7.0` (was 3.1.0 before)

**Comment by AdamHillier** [comment]
> thanks for trying to reproduce. it really is weird.
> just as additional hint, not sure if this is the cause though : I'm using `bazel 3.7.0-homebrew` and had to modify the .bazelversion to `3.7.0` (was 3.1.0 before)

Oh that could well be it. If you don't need any new features from Bazel, could you possibly try reverting the Bazel version file to `3.1.0` and installing [Bazelisk](https://docs.bazel.build/versions/master/install-bazelisk.html) and using that instead (as in `bazelisk build :build_pip_pkg`). It should then detect the version file and automatically download and use the correct Bazel binary for doing the build.

**Comment by simonmaurer** [comment]
so the build has finished.
did `bazel-bin/build_pip_pkg artifacts` and output is:

> + echo Tue Feb 2 18:15:41 CET 2021 : '=== Building wheel'
Tue Feb 2 18:15:41 CET 2021 : === Building wheel
+ python setup.py bdist_wheel
  File "setup.py", line 24
    raise ValueError(f"Invalid version: {version}")
                                                 ^
SyntaxError: invalid syntax

Will try as you suggested.

**Comment by AdamHillier** [comment]
> so the build has finished.
> did `bazel-bin/build_pip_pkg artifacts` and output is:
> 
> > * echo Tue Feb 2 18:15:41 CET 2021 : '=== Building wheel'
> >   Tue Feb 2 18:15:41 CET 2021 : === Building wheel
> > * python setup.py bdist_wheel
> >   File "setup.py", line 24
> >   raise ValueError(f"Invalid version: {version}")
> >   SyntaxError: invalid syntax

I think the syntax error might be coming from the f-string usage, which suggests `python configure.py` might have configured a < 3.6 version of Python? You could try adding `which python` as a line above [here](https://github.com/larq/compute-engine/blob/579c8fb02f69d6f08e1581206c7b9b00b5394028/build_pip_pkg.sh#L85) to check that the correct version is being used.

**Comment by simonmaurer** [comment]
within the virtual environment the `which python` command states :
> Python 3.7.7
so that should be correct when executing `python configure.py`

**Comment by simonmaurer** [comment]
so the compilation went fine this time. used bazelisk with bazel version 3.1.0, the initial error related to /tmp/android did not appear. good so far.
`bazel-bin/build_pip_pkg artifacts` also went through too, however when trying to install the generated pip wheel using:
`pip install larq_compute_engine-0.5.0-cp37-cp37m-macosx_10_14_x86_64.whl`:
> ERROR: larq_compute_engine-0.5.0-cp37-cp37m-macosx_10_14_x86_64.whl is not a supported wheel on this platform.

am I right to assume that the build commands for larq_compute_engine do not need a minimum OS version and should build automatically on the host ?
(I'm on 10.13.6 High Sierra and weirdly the pip wheel looks like it was built for 10.14)

**Comment by simonmaurer** [comment]
rerun to log output:

> Tue Feb 2 21:56:18 CET 2021 : === Building wheel
> + python setup.py bdist_wheel
warning: no files found matching '*.pyd' under directory 'larq_compute_engine'
[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 10_14 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:  
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/mlir/_graphdef_tfl_flatbuffer.so[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 10_14 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:  
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/mlir/_graphdef_tfl_flatbuffer.so+ cp dist/larq_compute_engine-0.5.0-cp37-cp37m-macosx_10_14_x86_64.whl /Volumes/MacData/similuke/dev/larq/larq_compute_engine/artifacts

**Comment by simonmaurer** [comment]
rerun to log output:

>Tue Feb 2 21:56:18 CET 2021 : === Building wheel
>+ python setup.py bdist_wheel
warning: no files found matching '*.pyd' under directory 'larq_compute_engine'
[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 10_14 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:  
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/mlir/_graphdef_tfl_flatbuffer.so[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 10_14 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:  
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
build/bdist.macosx-10.13-x86_64/wheel/larq_compute_engine-0.5.0.data/purelib/larq_compute_engine/mlir/_graphdef_tfl_flatbuffer.so+ cp dist/larq_compute_engine-0.5.0-cp37-cp37m-macosx_10_14_x86_64.whl ~/dev/larq/larq_compute_engine/artifacts

**Comment by AdamHillier** [comment]
Hmm, that is weird. I don't know why it would default to a higher value than your native OS version :/

That said, we successfully build release wheels for MacOS 10.13, you can see the command flags we pass in order to do that here: https://github.com/larq/compute-engine/blob/579c8fb02f69d6f08e1581206c7b9b00b5394028/.github/workflows/release.yml#L134-L135

**Comment by simonmaurer** [comment]
will compile again with these optimization flags

**Comment by simonmaurer** [comment]
so built again with exactly the aforementioned flags 

> Hmm, that is weird. I don't know why it would default to a higher value than your native OS version :/
> 
> That said, we successfully build release wheels for MacOS 10.13, you can see the command flags we pass in order to do that here:
> 
> https://github.com/larq/compute-engine/blob/579c8fb02f69d6f08e1581206c7b9b00b5394028/.github/workflows/release.yml#L134-L135

this time the compilation resulted in a correct`larq_compute_engine-0.5.0-cp37-cp37m-macosx_10_13_x86_64.whl`, installing it via pip in the virtual environment was successful.
importing larq_compute_engine in the python interpreter works as expected.

the only thing I noticed is when I'm directly in the root folder of the larq_compute_engine repo and starting the python interpreter. importing larq_compute_engine results in:

> ModuleNotFoundError: No module named 'larq_compute_engine.mlir._graphdef_tfl_flatbuffer'

**Comment by Tombana** [comment]
> one thing I noticed is when I'm directly in the root folder of the larq_compute_engine repo. launching the python interpreter and importing larq_compute_engine results in:
> 
> > import larq_compute_engine as lce
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File ".../larq_compute_engine/larq_compute_engine/**init**.py", line 1, in 
> > from larq_compute_engine.mlir.python.converter import convert_keras_model
> > File ".../larq_compute_engine/mlir/python/converter.py", line 6, in 
> > from larq_compute_engine.mlir._graphdef_tfl_flatbuffer import (
> > ModuleNotFoundError: No module named 'larq_compute_engine.mlir._graphdef_tfl_flatbuffer'
> 
> is that expected behavior?

This is expected. When in the root folder, the python import statement gives the `larq_compute_engine` folder higher priority than the package, and the `_graphdef_tfl_flatbuffer.so` (compiled library) file is not present there, it is only present in the compiled package.

**Comment by simonmaurer** [comment]
@Tombana perfect.

thank you all for the support. still wonder why such an error during compilation is thrown by newer versions than `bazel 3.1.0` but I consider this issue resolved

**Comment by simonmaurer** [comment]
perfect.

@Tombana, @AdamHillier thank you all for the support. still wonder why such an error during compilation is thrown by newer versions than `bazel 3.1.0` but I consider this issue resolved

**Comment by simonmaurer** [comment]
digged a bit deeper into that error.

it definitely is related to the following lines in the `WORKSPACE` file:
https://github.com/larq/compute-engine/blob/7b08c3005bfe651f57955d0e45a3c326ce5d1edd/WORKSPACE#L97-L103

starting with bazel version `3.5.0` the error as follows is thrown:

> Analysis of target '//larq_compute_engine/tflite/benchmark:lce_benchmark_model' failed; build aborted: The repository's path is "/tmp/lce_android" (absolute: "/tmp/lce_android") but a symlink could not be created for it, because: /tmp/lce_android (No such file or directory)

every other version until `bazel 3.4.1` does not throw this error.
the Java function responsible for this is here:
https://github.com/bazelbuild/bazel/blob/7cfe416c5b702967b63cb2d9e2a2a2aefb8d2cac/src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryFunction.java#L488-L492

checked the changelog of `bazel 3.5.0`, according to the docs it should be backward-compatible

when removing the cmd `android_workspace` in [WORSKPACE](https://github.com/larq/compute-engine/blob/master/WORKSPACE) even with bazel versions post `3.4.1`

**Comment by AdamHillier** [comment]
Hi @simonmaurer, sorry for the delay in getting back to you. Thanks for investigating the Bazel errors further :)

My gut instinct, without any evidence, is that this is a bug in Bazel that has been introduced, since as you say that release is meant to be backwards-compatible. Unfortunately, it's hard to have any insight in how to get this working with newer Bazel versions without actually trying to do upgrade. Since TensorFlow master is currently on Bazel 3.7.2, we will certainly have to address this when we update our TF dependency (which we probably do when/soon after the TF 2.5 release branch gets cut).

It's true that our approach of hard-coding this link to `/tmp/lce_android` is not the approach TF takes (perhaps it once was); they have dynamic configuration of paths to Android SDK/NDK environments as [part of their `configure.py`](https://github.com/tensorflow/tensorflow/blob/b299b2600d2be042aa8604f83ef494cea91adb4d/configure.py#L698-L835), so likely the easiest thing for us to do would be to copy these functions into our own `configure.py` and delete the hard-coded lines. Of course, that's actually a much nicer solution anyway since it's much less brittle and allows interactive configuration.
