### ISSUE TITLE
Support for macos_arm64

### ISSUE THREAD

**Issue by simonmaurer** [larq/compute-engine#604]
tried to run [lce_benchmark_model](https://docs.larq.dev/compute-engine/benchmark/) on an Apple Mac mini with M1.
turns out that this is not possible directly although the platform `aarch64` is generally the same.

next step was trying to build it manually but it did not work since more adaptations for the `bazel` build system are needed (I assume it would need a different toolchain).

could you give me a hint on how to implement this properly such that we could do:

> bazel build --config=macos_arm64 //larq_compute_engine/tflite/benchmark:lce_benchmark_model

or for the whole pip package of `larq_compute_engine`

> bazel build --config=macos_arm64 :build_pip_pkg

since commit [bab0d14036efd0adcd4e48303d045cee3c342cb0](https://github.com/tensorflow/tensorflow/pull/45404/commits/bab0d14036efd0adcd4e48303d045cee3c342cb0) it is possible
 to build TF2.4 for Apple silicon as explained [here](https://github.com/tensorflow/tensorflow/pull/45404).
I checked the subrepo of TF within `larq_compute_engine`, which currently is at commit [85c8b2a817f95a3e979ecd1ed95bff1dc1335cff](https://github.com/tensorflow/tensorflow/tree/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff) so this is not yet included

**Comment by lgeiger** [comment]
Unfortunately we are not able to give you concrete guidance here as we don't have access to Apple Silicon at the moment.

From the PR you linked it should be possible to update the TensorFlow dependency to a newer commit [here](https://github.com/larq/compute-engine/blob/14da1c84c9cc8269fe12ba2c210ab1c70f0f4a3d/WORKSPACE#L41-L55), although I am not sure if this would require additional changes to our code.
Then, you probably need to manually apply the changes of the PR to our [`.bazelrc`](https://github.com/larq/compute-engine/blob/master/.bazelrc) and add the missing platform `config_setting` [here](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/BUILD).

I would start with `lce_benchmark_model` as it has a lot fewer dependencies that could lead to problems.

**Comment by simonmaurer** [comment]
so for a start I changed the `.bazelrc` and `CONFIG` according to these PR changes.
since you mentioned updating the SHA hash [here](https://github.com/larq/compute-engine/blob/14da1c84c9cc8269fe12ba2c210ab1c70f0f4a3d/WORKSPACE#L41-L55): is larq compiled using TF by downloading that .tar.gz package ?
cause I also thought I had to update the [tensorflow subrepo](https://github.com/larq/compute-engine/tree/master/third_party) to that newer commit.

**Comment by AdamHillier** [comment]
Hey Simon, when building with Bazel the tar.gz file that's in the WORKSPACE file you linked to gets used, and the TF submodule is used for Makefile builds. We tend to use Bazel for almost everything so the WORKSPACE file is what matters, but when we update TF versions we always bump the submodule as well to keep them in sync.

**Comment by simonmaurer** [comment]
so workin on this front also revealed some updates.
1. bazel: with the aforementioned changes in `WORKSPACE` using a more recent TF (mid January) tar.gz and [BUILD](https://github.com/larq/compute-engine/blob/master/larq_compute_engine/core/bitpacking/BUILD) I was able to build the `lce_minimal` example. however `lce_benchmark_model`/`pip_package` do not work yet (also tried compiling the lce_benchmark_model from offical TF repo) which resulted in errors with respect to XNNPACK. (the bazel compilation automatically builds with xnnpack whereas LCE make script does not). this is due to XNNPACK not being able to build using `bazel`, check this [issue](https://github.com/google/XNNPACK/issues/1302)
2. make: with the aforementioned changes I was able to compile the `lce_benchmark_model` for `macos_arm64`using

> larq_compute_engine/tflite/build_make/build_lce.sh --native

this works and I evaluated the QuickNet models. the performance is quite stunning. [LARQ doc](https://docs.larq.dev/compute-engine/) would also be a nice place to show these numbers

3. I made a [pull request](https://github.com/tensorflow/tensorflow/pull/47437) on the official TF repo to allow a host compilation using cmake for `TensorFlow Lite library` and the `benchmark_model` on `macos_arm64`.

**Comment by simonmaurer** [comment]
@lgeiger @Tombana @AdamHillier as stated above bazel builds are not yet possible (due to TensorFlow Lite dependencies on [XNNPACK](https://github.com/google/XNNPACK) but I issued a [PR](https://github.com/google/XNNPACK/pull/1327) there.

once this gets accepted, I can issue a PR in the official [TensorFlow](https://github.com/tensorflow/tensorflow) repo. this should allow bazel builds of the `TensorFlow Lite library`and the `benchmark_model` for the `macos_arm64`platform.

**Comment by simonmaurer** [comment]
Closing this issue as #664 fixes this and has been merged
