### ISSUE TITLE
Converting to TensorRT for Jetson Nano

### ISSUE THREAD

**Issue by tehtea** [larq/compute-engine#609]
Hi all, is it possible to run the LCE on the Jetson Nano using TensorRT by any chance? Currently, I managed to compile the benchmark tool from source on it but as far as I know the inference using that binary only relies on the CPU.

**Comment by Tombana** [comment]
Hi @tehtea,

LCE only contains optimized binary convolutions for ARM Cortex-A CPU's. So you are right, if you managed to compile it for the Jetson Nano, it will only have optimized CPU kernels and no GPU kernels. GPU support is not in the planning, but we welcome pull requests from the community in case you want to write a GPU implementation.

**Comment by tehtea** [comment]
Thanks for the quick response! Just wanted to confirm, no promises on writing the implementation and making the PR.
