### ISSUE TITLE
Model is unexpectedly big after conversion

### ISSUE THREAD

**Issue by LJHG** [larq/compute-engine#631]
Hi, I'm running the official demo **BinaryNet on CIFAR10**  on your website.
According to the summary, the model after conversion is supposed to be 1.26MB. However, I got 23.7MB in the size.
This is much bigger than expected, is there anything wrong with my code?
Any reply would be appreciated! 
The code is here:
```python
import tensorflow as tf
import larq as lq
import numpy as np
import matplotlib.pyplot as plt
import larq_compute_engine as lce


# All quantized layers except the first will use the same options
kwargs = dict(input_quantizer="ste_sign",
              kernel_quantizer="ste_sign",
              kernel_constraint="weight_clip",
              use_bias=False)

model = tf.keras.models.Sequential([
    # In the first layer we only quantize the weights and not the input
    lq.layers.QuantConv2D(128, 3,
                          kernel_quantizer="ste_sign",
                          kernel_constraint="weight_clip",
                          use_bias=False,
                          input_shape=(32, 32, 3)),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantConv2D(128, 3, padding="same", **kwargs),
    tf.keras.layers.MaxPool2D(pool_size=(2, 2), strides=(2, 2)),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantConv2D(256, 3, padding="same", **kwargs),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantConv2D(256, 3, padding="same", **kwargs),
    tf.keras.layers.MaxPool2D(pool_size=(2, 2), strides=(2, 2)),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantConv2D(512, 3, padding="same", **kwargs),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantConv2D(512, 3, padding="same", **kwargs),
    tf.keras.layers.MaxPool2D(pool_size=(2, 2), strides=(2, 2)),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),
    tf.keras.layers.Flatten(),

    lq.layers.QuantDense(1024, **kwargs),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantDense(1024, **kwargs),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),

    lq.layers.QuantDense(10, **kwargs),
    tf.keras.layers.BatchNormalization(momentum=0.999, scale=False),
    tf.keras.layers.Activation("softmax")
])

lq.models.summary(model)

model.save("binaryNet.h5")

m = tf.keras.models.load_model("binaryNet.h5")
lq.models.summary(m)
with open("binaryNet.tflite", "wb") as flatbuffer_file:
    flatbuffer_bytes = lce.convert_keras_model(m)
    flatbuffer_file.write(flatbuffer_bytes)
```

**Comment by AdamHillier** [comment]
Hey @LJHG, I believe in this case almost all of the model size in the converted model comes from the (very large) fully connected layers at the end of the network.

Despite the fact that they are Larq `QuantDense` layers, Larq Compute Engine doesn't currently implement a binarised version of these. As a result, those layers are converted to float32 fully connected layers, which means that the weights are 32x bigger they would be in a optimised binary fully connected layer.

One workaround is to replace your `QuantDense` layers with equivalent `QuantConv2D` layers. This can be done by reshaping to `(batch_size, 1, 1, num_channels_in)`, applying a `QuantConv2D` with `kernel_size=1`, then reshaping to `(batch_size, 1, 1, num_channels_out)`. If you do this, then the converted model size should be much smaller.

Let me know if you have any problems with this or have any other questions :)

**Comment by LJHG** [comment]
@AdamHillier ,Thanks for the reply, it really helps. I have tried and it worked out :)

**Comment by AdamHillier** [comment]
Great to hear, I'm going to close this now but feel free to re-open if you run into any more issues
