### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by Tombana** [larq/compute-engine#66]
Before we make the compute engine public, we should make sure we include proper licenses for all the things we are using, which is for now tensorflow and all the things it depends on.
For example, daBNN includes all kinds of indirect dependencies in its LICENSE file such as Eigen and Flatbuffers.

**Comment by AdamHillier** [comment]
Is this not still an outstanding issue?

It seems to me that there are still some license issues with LCE.

One example I've found is [this file](https://github.com/larq/compute-engine/blob/bdd3c080ea330ad911cfb6b02dd41b6c574a7cf4/larq_compute_engine/tflite/benchmark/lce_benchmark_main.cc), which includes a TensorFlow copyright notice at the top, but has been modified by us (line 19 at the very least). Section 4b of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0) is clear that in this scenario we need to give "prominent notice" that we changed the file. This is easy: we could for example simply add a line to the existing comment with `Modifications copyright 2020 Larq Contributors` or something like that. This same issue may apply to [multiple other files in this repo](https://github.com/larq/compute-engine/search?q=%22TensorFlow+Authors%22&unscoped_q=%22TensorFlow+Authors%22).

**Comment by Tombana** [comment]
Thanks for spotting that @AdamHillier . From what I can see:

- `larq_compute_engine/tflite/benchmark/lce_benchmark_main.cc ` There's indeed a few lines that changed so I think @AdamHillier 's suggestion is good there.
- `larq_compute_engine/tflite/tests/bconv2d_test.cc`   there the notice can be removed I think, as this is almost entirely our own file (simply inspired from a tflite unittest)
- `configure.sh`  this notice can also be removed i think. Although the file started out as an exact copy, it is now quite different.
- `build_pip_pkg.sh` This file is still close to the original except for some strings "Larq Compute Engine", so probably Adams suggestion also applies here.

**Comment by AdamHillier** [comment]
> * `larq_compute_engine/tflite/tests/bconv2d_test.cc`  there the notice can be removed I think, as this is almost entirely our own file (simply inspired from a tflite unittest).
> * `configure.sh`  this notice can also be removed i think. Although the file started out as an exact copy, it is now quite different.

I know this is very pernickety, but if there's a commit history that shows a link from the original file to our version, even if the contents is almsost completely re-written, it might be best to err on the side of caution (I feel this more strongly with the second case than with the first).
