### ISSUE TITLE
Permission denied when benchmarking on Android using ADB

### ISSUE THREAD

**Issue by rameshKrSah** [larq/compute-engine#665]
Hi, I tried the benchmark tool for Android using ADB, and I couldn't run the tool because of the permission denied error. 

![image](https://user-images.githubusercontent.com/21354640/122248100-b0a80500-ce7c-11eb-8152-d4188b63ffd8.png)

The solution was to make the benchmark tool executable using the ADB shell like this:

![image](https://user-images.githubusercontent.com/21354640/122248321-daf9c280-ce7c-11eb-8a5a-2b2958d574ce.png)

After this, the tool runs fine and prints out the evaluation results. 

![image](https://user-images.githubusercontent.com/21354640/122248497-f2d14680-ce7c-11eb-96e1-9c499aa417a7.png)

I just want to put this out here to help others facing the same problem. 

An update to the docs here (https://docs.larq.dev/compute-engine/benchmark/) will be the permanent fix.

**Comment by lgeiger** [comment]
Thanks for catching this. I wasn't aware that the permissions might get lost on some phones or adb servers when pushing the benchmarking binary.

@rameshKrSah Do you want to sent a PR to [add this to the docs here](https://github.com/larq/docs/blob/master/docs/compute-engine/benchmark.md)?

**Comment by lgeiger** [comment]
> I wasn't aware that the permissions might get lost on some phones or adb servers when pushing the benchmarking binary.

Actually this might be due to Windows. I think we only tested the docs on Linux and macOS. Either way we should update the docs to change the permissions on the phone instead 👍

**Comment by rameshKrSah** [comment]
> Thanks for catching this. I wasn't aware that the permissions might get lost on some phones or adb servers when pushing the benchmarking binary.
> 
> @rameshKrSah Do you want to sent a PR to [add this to the docs here](https://github.com/larq/docs/blob/master/docs/compute-engine/benchmark.md)?

Sure, I can do that. Will send the PR soon. :)

**Comment by rameshKrSah** [comment]
The pull request was [merged ](https://github.com/larq/docs/pull/278)
