### ISSUE TITLE
aarch64-linux-gnu-ar command not found when building compute engine with make for aarch64 

### ISSUE THREAD

**Issue by rameshKrSah** [larq/compute-engine#676]
Just wanted to share this error and the solution when building the compute engine with make for 64bit arm on Manjaro running on PI4. 

The solution was to specify `AR=ar` in the `build_lce.sh` script. Specifically, I changed the line 136 with 

`
    make -j ${NUM_HYPERTHREADS} TARGET=aarch64 AR=ar -C "${TF_DIR}" -f tensorflow/lite/tools/make/Makefile
`

I don't have a good understanding of building with make and I hope someone can shed more light on this issue. I found the solution by reading [this](https://github.com/adoptium/temurin-build/issues/1105).

**Comment by Tombana** [comment]
Thanks for sharing this fix!
I think we've seen a similar problem before, also on 64-bit Manjaro for rpi. I think when that happened it was not specifically for `ar` but for `gcc` in general.
In our docs, at the very bottom of this page https://docs.larq.dev/compute-engine/build/arm/, we have instructions for renaming `aarch64-unknown-gnu-XXX` to `aarch64-linux-gnu-XXX`. I think that would also have solved it.
