### ISSUE TITLE
Upgrade TensorFlow dependency to 2.6

### ISSUE THREAD

**Issue by lgeiger** [larq/compute-engine#680]
The TensorFlow 2.6 stable has been released. It would be good to upgrade to this release at some point.

**Comment by Tombana** [comment]
The TFMicro project moved to a standalone repo, so we probably first have to address that.

**Comment by lgeiger** [comment]
> The TFMicro project moved to a standalone repo, so we probably first have to address that.

Good point. Although, it looks like the 2.6 release still includes the micro code in the monorepo: https://github.com/tensorflow/tensorflow/tree/v2.6.0/tensorflow/lite/micro so maybe it still works.

**Comment by Tombana** [comment]
Great, then I was mistaken and there's no problem yet.
