### ISSUE TITLE
Automatic release builds for benchmarking binaries are broken

### ISSUE THREAD

**Issue by lgeiger** [larq/compute-engine#682]
Currently our release builds on CI for the benchmarking binaries are broken. See [here](https://github.com/larq/compute-engine/runs/3535332573?check_suite_focus=true) for more info.

**Comment by Tombana** [comment]
I think this has been the case for our private release builds for about 6 months already, with similar error messages. This was weird because the public release builds were still succeeding 2 months ago.

**Comment by CNugteren** [comment]
This is no longer the case since the TF 2.8 update I believe, see e.g. this successful build:
https://github.com/larq/compute-engine/actions/runs/2220640761

I'm therefore closing this issue.
