### ISSUE TITLE
Deployment on Cortex-M

### ISSUE THREAD

**Issue by mengna0707** [larq/compute-engine#688]
Hi, I'm in a bit of a hurry， so I‘m asking here  who I should contact for details if I want to use the deployment tool on the ARM Cortex-M family of MCUs.

**Comment by CNugteren** [comment]
Hello mengna0707. Thank you for your interest in the Larq Compute Engine.

The open-source version of the Larq Compute Engine does not support deployment on Cortex-M. If you are interested in inference on Cortex-M, please contact our sales team at hello@plumerai.com and we'll get into contact with you. In your email please provide relevant details such as the kinds of neural networks you are planning to use, the exact target board(s) and an estimation of the amount of devices you are planning to deploy onto.
