### ISSUE TITLE
Error while  performing benchmarking

### ISSUE THREAD

**Issue by sandeep1404** [larq/compute-engine#770]
Hello all, 
I am having raspberry pi 3b+ installed with 32bit raspbian os  when I try to do benchmarking from the documentation [https://docs.larq.dev/compute-engine/benchmark/](url) I am getting the following error as shown in the picture.
```
pi@pi:~/Desktop $ chmod +x lce_benchmark_model
pi@pi:~/Desktop $ ./lce_benchmark_model --graph=quicknet.tflite --num_threads=4
./lce_benchmark_model: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by ./lce_benchmark_model)
./lce_benchmark_model: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by ./lce_benchmark_model)
./lce_benchmark_model: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.32' not found (required by ./lce_benchmark_model)
./lce_benchmark_model: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by ./lce_benchmark_model)
./lce_benchmark_model: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./lce_benchmark_model)
./lce_benchmark_model: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./lce_benchmark_model)
pi@pi:~/Desktop $ 

```
ldd --version gives ```ldd (Debian GLIBC 2.28-10)2.28  ```

Also the process for performing inference on raspberry pi is not so clear for me. I trained my own model using larq library, converted the model to tflite format as given in end to end guide [https://docs.larq.dev/compute-engine/end_to_end/](url),  but after generating the tflite , I am struck what to do, how to perform inference using this tflite file on raspberry pi. I was looking at building models for arm [https://docs.larq.dev/compute-engine/build/arm/](url) , but I am not able to perform inference. Can anyone please guide me how to perform inference on raspberry pi board and please help in resolving the issue. Thank you in advance.

**Comment by Tombana** [comment]
Hi @sandeep1404, thanks for trying out Larq Compute Engine!

The `lce_benchmark_model` binary requires a more recent C library than the one that comes with Raspbian. So you either need to install a more recent OS, or compile `lce_benchmark_model` on the Raspberry Pi itself. The instructions for that can be found here: https://docs.larq.dev/compute-engine/build/arm/ under the tab 'Building with CMake'

The documentation for doing inference is here: https://docs.larq.dev/compute-engine/inference/

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for the reply, I have raspberry pi 4 loaded with 64bit os, when I try to build with cmake, the first step is to clone the Larq Compute Engine repository and make sure the TensorFlow submodule is loaded: 
So I cloned the LCE and when I try the below command for TensorFlow submodule to be loaded it got struck at that point.
```
git submodule update --init
```
```
Submodule 'tensorflow' (https://github.com/tensorflow/tensorflow.git) registered for path 'third_party/tensorflow'
Cloning into '/home/pi/larq/compute-engine/third_party/tensorflow'...
```
It got struck since from long time saying that its cloning. Whats the issue am I gng in right direction, can you please help me in this regard. Thank you in advance.

**Comment by sandeep1404** [comment]
Hi @Tombana  Thanks for the reply, I have a question, I built a larq model for image denoising, the model is working well for image denoising, now I converted the model to tflite  and I want to perform inference on raspberry pi using larq compute engine, so as per my understanding I need to perform the following steps, please correct me If I am wrong :
1. I converted my Image denoising model to tflite model using larq converter
2. I build with cmake on raspberry pi 4 with 64bit os
3. Now after building I need to perform inference using C++ using the documentation  [https://docs.larq.dev/compute-engine/inference/](url) 

Are these steps correct, and can we perform image denoising inference on raspberry pi since its a kind of regression problem, I see all image classification problems performing inference on raspberry pi using larq compute engine.

Also, I am not able to get a clear picture on how to perform inference on our custom model using C++ since it is unclear from the documentation, I checked the example [https://github.com/larq/compute-engine/tree/main/examples](url) but still its not so clear about the process of performing Image denoising inference on raspberry pi using LCE. please help me in this regard. Thanks in advance

**Comment by Tombana** [comment]
Q1: This is correct.

Q2: The example is not for image classification in particular, it is for general inference. You still have to add code that generates the input to the neural network and code that handles the output.

Q3: This is possible using our "testing" interpreter, see here: https://docs.larq.dev/compute-engine/api/python/#interpreter . To get that to work on aarch64, please see this issue: https://github.com/larq/compute-engine/issues/653

**Comment by sandeep1404** [comment]
Hi @Tombana  Thanks for the reply. So using the testing interpreter based on python API as mentioned in [https://docs.larq.dev/compute-engine/api/python/#interpreter](url), so this interpreter testing code is as follows which accepts the tflite file as input
```
larq_compute_engine.testing.Interpreter(
    flatbuffer_model,
    num_threads=1,
    use_reference_bconv=False,
    use_indirect_bgemm=False,
    use_xnnpack=False,
)

lce_model = convert_keras_model(model)
interpreter = Interpreter(lce_model)
interpreter.predict(input_data, verbose=1)

```
do I need to run all these codes on raspberry pi for inference, since if I run all these codes on my CPU it doesn't make any difference in inference time is that correct?

**Comment by Tombana** [comment]
You can run the `convert_keras_model` part on your other computer. The `interpreter.predict(..)` part is what you can run on the Raspberry Pi.

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for the reply, I got it now. But what is the difference between doing inference with C++ as mentioned in [https://github.com/larq/compute-engine/issues/url](url) and inference using python API [https://github.com/larq/compute-engine/issues/url](url), are the both same or different? Thank you in adavance

**Comment by Tombana** [comment]
The C++ and Python versions both do the same. However the Python version has more overhead, so if latency is crucial then you could use C++.
Indeed the `larq-compute-engine` package is not available on the RPi4 by default, but here it is explained how you can compile it yourself: https://github.com/larq/compute-engine/issues/653

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for answering all my queries patiently.  I have gone through #653 and started building pip package for lce as mentioned in that by removing  few of the code lines as mentioned in the issue #653, I performed the following steps:

when I perform the bazel build using the below command it got build completed sucessfully
```
bazel build :build_pip_pkg --config=aarch64
```
after that bazel-bin directory got created but the directory is empty and when I ran the below command it gives me an error showing that no such file or directory. I am attaching the picture for the reference.
![IMG_20230420_111407](https://user-images.githubusercontent.com/45798709/233270061-939e2bb8-09a1-4cb8-81aa-2e5ab3103219.jpg)

```
bazel-bin/build_pip_pkg artifacts --plat=linux_aarch64
```
What is the issue, can you please help in resolving the issue and how to verify whether the pip package for LCE is installed or not?

**Comment by CNugteren** [comment]
I believe the issue might be the first output after `bazel build :build_pip_pkg --config=aarch64`:
```
WARNING: Download from https://..... GET returned 404 Not Found
```
Do you have a working internet connection on your device? If so, perhaps just re-try again later.

**Comment by sandeep1404** [comment]
Hi @CNugteren Thanks for the reply, My board is connected to the internet, I retired building again using the command   
  ```bazel build :build_pip_pkg --config=aarch64``` but still it gives me the same warning as mentioned in the picture and then said build completed successfully : 
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/... GET returned 404 Not Found
```

**Comment by sandeep1404** [comment]
Hi @Tombana  Thanks for the reply, there are some files in bazel-out directory but I cannot able to see any files in bazel-bin even when I used ```run``` instead of ```build```. when  I use run it got run but there are no files in bazel-bin
I am attaching the picture for the reference 
![bazel](https://user-images.githubusercontent.com/45798709/233291085-a70e5e67-f214-4cdc-8de5-86f89cc5efdd.jpg)
Please have a look into it and kindly help me in this regard, Thank you in advance.

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for the response, I checked the contents of ```bazel-out/aarch64-opt``` and its subfolder, there is nothing in it, also I run the command ```bazel info bazel-bin``` and checked the path and there is nothing inside that path as well, I am attaching the picture for your kind reference. Thank you in advance.
![bazel1](https://user-images.githubusercontent.com/45798709/233331811-11054efc-73d6-4bfc-97a3-42518c749742.png)

**Comment by Tombana** [comment]
I have searched a bit but I'm afraid I don't have a solution. Since you're building on the raspberry pi itself, maybe it works if you remove the `--config=aarch64` flag from bazel build.

**Comment by sandeep1404** [comment]
Hi, @Tombana Thanks for the reply, I followed all your steps but still, I cannot able to find anything in the``` Bazel-bin``` directory, but I found the ``` build_pip_package.sh``` file in``` Bazel-compute-engine``` and when I tried to execute the command It was giving me the error, I am attaching the pictures for reference, can you please have a look at it, and if you can able to debug the issue please help in resolving this, or is there is any other way where I can run the inference on raspberry pi using python API, any clear example would be beneficial to understand. Thanks for the help.
![bazel2](https://user-images.githubusercontent.com/45798709/233350285-e7c7c703-2bc4-4650-8ea0-4eac2078e24c.png)
![bazel3](https://user-images.githubusercontent.com/45798709/233350313-6f14dcb0-706c-4769-8c8d-0656b5e105f2.png)

**Comment by Tombana** [comment]
Those bazel errors that you get with `bazel build //larq_compute_engine/tflite/python:interpreter` are the problem. (I think maybe also you modified some BUILD files where you excluded `//larq_compute_engine/tflite/python:interpreter` from `build_pip_pkg` or something, otherwise this error would've shown up before).

I think the problem might be the version of bazel. Can you try to use bazelisk instead of bazel?
Download it from https://github.com/bazelbuild/bazelisk/releases and then replace the `bazel` command with `./bazelisk`

**Comment by Tombana** [comment]
I'm afraid I don't have any other ideas. I'm pretty sure that the errors at `bazel build //larq_compute_engine/tflite/python:interpreter` are the main problem, but I don't know how to fix that. I've never tried to use bazel directly on a Raspberry Pi.
I think it might be easier to just build the RPi package on your other computer instead of building it on the RPi itself. Then you need `--config=aarch64` so that it will build for aarch64.

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for the reply, I will try the other way in building the package on another computer and try to config on RPi, I will post if I face any further issues, Thank you for the help and patience in looking at the issues.

**Comment by sandeep1404** [comment]
Hi @Tombana I am confused about how to build the package on another computer and try to config on RPi, can you give me an insight in understanding the process of how to do that? Thanks in advance.

**Comment by Tombana** [comment]
It's the same steps as on the Pi itself, except that you have to use `--config=aarch64` when you run `bazel build`. And when you run the python wheel packaging step, you have to use `--plat=linux_aarch64`, as described in https://github.com/larq/compute-engine/issues/653.

**Comment by sandeep1404** [comment]
Hi @Tombana Thanks for the reply, is there any example or any repo for end to end guide for deploying a custom BNN model on raspberry pi with Larq compute engine doing inference with Python API, if so can you please share it here, Thank you in advance.

**Comment by sandeep1404** [comment]
Hi @Tombana I am trying to build the package on Ubuntu 20.04, using the command ```bazel build :build_pip_pkg --config=aarch64``` but the build was not successful I am attaching the picture that shows logs for error 
![bazel error (1)](https://user-images.githubusercontent.com/45798709/234341061-c11e3bca-dd9e-42df-8dcb-9f7e9e6fc3de.png)
Can you please have a look and help me in resolving the issue, Thank you in advance.

**Comment by sandeep1404** [comment]
Hi @Tombana I followed the instructions specified in #653 to build the pip package in Ubuntu 20.04, I followed the below steps:
**step1**:
 build using the command ```bazel build :build_pip_pkg --config=aarch64```  the following are the logs on my system with Ubuntu:
```
WARNING: Option 'java_toolchain' is deprecated
WARNING: Option 'host_java_toolchain' is deprecated
INFO: Analyzed target //:build_pip_pkg (9 packages loaded, 68 targets configured).
INFO: Found 1 target...
Target //:build_pip_pkg up-to-date:
  bazel-bin/build_pip_pkg
INFO: Elapsed time: 4.005s, Critical Path: 0.89s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
```

After a successful build I found files in bazel-bin, where earlier when I build on RPi I cannot able to find the files in bazel-bin 
 **step 2:**
Next I ran this command  on my computer ```bazel-bin/build_pip_pkg artifacts --plat=linux_aarch64``` and below are the logs for the command
```
++ uname -s
++ tr A-Z a-z
+ PLATFORM=linux
+ is_windows
+ [[ linux =~ msys_nt*|mingw*|cygwin*|uwin* ]]
+ PIP_FILE_PREFIX=bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/
+ main artifacts --plat=linux_aarch64
+ DEST=artifacts
+ BUILD_FLAG=--plat=linux_aarch64
+ [[ -z artifacts ]]
+ mkdir -p artifacts
++ abspath artifacts
+++ dirname artifacts
++ cd .
+++ basename artifacts
++ echo /home/sandeep/compute-engine/artifacts
++ cd /home/sandeep/compute-engine
+ DEST=/home/sandeep/compute-engine/artifacts
+ echo '=== destination directory: /home/sandeep/compute-engine/artifacts'
=== destination directory: /home/sandeep/compute-engine/artifacts
++ mktemp -d -t tmp.XXXXXXXXXX
+ TMPDIR=/tmp/tmp.T5Njh7hkNJ
++ date
+ echo Tuesday 25 April 2023 10:45:43 PM IST : '=== Using tmpdir: /tmp/tmp.T5Njh7hkNJ'
Tuesday 25 April 2023 10:45:43 PM IST : === Using tmpdir: /tmp/tmp.T5Njh7hkNJ
+ echo '=== Copy Larq Compute Engine files'
=== Copy Larq Compute Engine files
+ cp bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/setup.py /tmp/tmp.T5Njh7hkNJ
+ cp bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/MANIFEST.in /tmp/tmp.T5Njh7hkNJ
+ cp bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/README.md /tmp/tmp.T5Njh7hkNJ
+ cp bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/LICENSE /tmp/tmp.T5Njh7hkNJ
+ is_linux
+ [[ linux == \l\i\n\u\x ]]
+ touch /tmp/tmp.T5Njh7hkNJ/stub.cc
+ is_windows
+ [[ linux =~ msys_nt*|mingw*|cygwin*|uwin* ]]
+ rsync -avm -L '--exclude=*_test.py' bazel-bin/build_pip_pkg.runfiles/larq_compute_engine/larq_compute_engine /tmp/tmp.T5Njh7hkNJ
building file list ... done
larq_compute_engine/
larq_compute_engine/__init__.py
larq_compute_engine/mlir/
larq_compute_engine/mlir/__init__.py
larq_compute_engine/mlir/python/
larq_compute_engine/mlir/python/__init__.py
larq_compute_engine/tflite/
larq_compute_engine/tflite/__init__.py
larq_compute_engine/tflite/python/
larq_compute_engine/tflite/python/__init__.py
larq_compute_engine/tflite/python/interpreter.py
larq_compute_engine/tflite/python/interpreter_base.py
larq_compute_engine/tflite/python/interpreter_wrapper_lite.so

sent 3,704,866 bytes  received 183 bytes  7,410,098.00 bytes/sec
total size is 3,703,194  speedup is 1.00
+ pushd /tmp/tmp.T5Njh7hkNJ
/tmp/tmp.T5Njh7hkNJ ~/compute-engine
+ is_windows
+ [[ linux =~ msys_nt*|mingw*|cygwin*|uwin* ]]
+ echo '=== Stripping symbols'
=== Stripping symbols
+ chmod +w /tmp/tmp.T5Njh7hkNJ/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
+ strip -x /tmp/tmp.T5Njh7hkNJ/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so
strip: Unable to recognize the format of the input file `/tmp/tmp.T5Njh7hkNJ/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so'
```
These are the different folders in Bazel bin 
```
build_pip_pkg  build_pip_pkg.runfiles  build_pip_pkg.runfiles_manifest  examples  external  larq_compute_engine
```
I am unaware of what to do next, what files need to be copied and where they are located and how to install those files on RPi and do inference using python based interpreter.

**Comment by bywmm** [comment]
> The `lce_benchmark_model` binary requires a more recent C library than the one that comes with Raspbian. So you either need to install a more recent OS, or compile `lce_benchmark_model` on the Raspberry Pi itself. The instructions for that can be found here: https://docs.larq.dev/compute-engine/build/arm/ under the tab 'Building with CMake'
> 
> The documentation for doing inference is here: https://docs.larq.dev/compute-engine/inference/

Hi there, I have the same problem with the Raspberry Pi OS Lite (64-bit), which was released on 2023-02-21. Is there any suggestion for which OS I should use?

**Comment by Tombana** [comment]
@sandeep1404 
It seems like the `strip` utility does not accept aarch64 libraries. Can you comment-out the `strip` command from the `build_pip_package.sh` script, and then try to run it again?
Once that's successful, a `.whl` file should appear in the folder `artifacts`. You can copy that `.whl` file to your raspberry pi and then just use `pip install ./filename.whl` on it.

> Hi there, I have the same problem with the Raspberry Pi OS Lite (64-bit), which was released on 2023-02-21. Is there any suggestion for which OS I should use?

Hi @bywmm, I recommend Manjaro Linux (easy setup) or Arch Linux (for more advanced users) for Raspberry Pi. These distributions usually come with the newest packages.

**Comment by Tombana** [comment]
It seems like `--plat=linux_aarch64` might be ignored by the python tools. Can you try to update the `setuptools` and `wheel` packages?
```
pip install setuptools wheel --upgrade
```

**Comment by sandeep1404** [comment]
Hi @Tombana, I tried  updating the setup tools and wheel with the command ```pip install setuptools wheel --upgrade``` , but still I am facing the same issue as mentioned in above: ``` ERROR: larq_compute_engine-0.11.0-cp310-cp310-linux_x86_64.whl is not a supported wheel on this ```. What is the issue, can you please help me in resolving this issue? Thank you in advance.

**Comment by Tombana** [comment]
I meant upgrading those packages on your Ubuntu machine, and then recreating the `.whl` file.

**Comment by Tombana** [comment]
Maybe it's a python version mismatch? I see that you built a python 3.10 wheel on your Ubuntu machine. Maybe the raspberry Pi has another python version? They have to be the same.

**Comment by sandeep1404** [comment]
Hi @Tombana, I created a new environment with python=V3.9 and build the packages, now the .whl file ran successfully and installed larq_compute_engine-0.11.0, but when I try to import lce ```import larq_compute_engine as lce``` it is throwing me a Module not found error as shown in the figure below. What are the next steps, is the LCE installed properly, can I load the interpreter and run the inference now. Sorry for troubling you 
by asking many questions this is a part of my thesis work, So I need to resolve and do inference. Thank you in advance.
![lce](https://user-images.githubusercontent.com/45798709/234562502-daa7bf90-2efe-4c38-82fe-15b2e5d9dc8d.png)

**Comment by Tombana** [comment]
As described in https://github.com/larq/compute-engine/issues/653, you have to remove `from larq_compute_engine.mlir.python.converter import convert_keras_model` from `__init__.py` and remove `convert_keras_model` from `__all__`, that should fix this issue.

**Comment by sandeep1404** [comment]
Hi @Tombana , I started Performing Inference on RPI, I converted the model to tflite on my computer and loaded the tflite file on RPI, but I am getting the following error:

```
Traceback (most recent call last):
  File "/home/pi/larq/larq_bnn_test/larq_bnn_test.py", line 10, in <module>
    interpreter=lce.testing.Interpreter(
  File "/home/pi/.local/lib/python3.9/site-packages/larq_compute_engine/tflite/python/interpreter.py", line 48, in __init__
    from larq_compute_engine.tflite.python import interpreter_wrapper_lite
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/pi/.local/lib/python3.9/site-packages/larq_compute_engine/tflite/python/interpreter_wrapper_lite.so)
```
I have lib6 and lib6-dev already installed 
```
libc6 is already the newest version (2.31-13+rpt2+rpi1+deb11u5).
libc6-dev is already the newest version (2.31-13+rpt2+rpi1+deb11u5).
```
I have no clue how to resolve this issue, I have GLIBC 2.31 installed in my system, it is the latest version, but it ask for GLIBC_2.32. Can you kindly help me in resolving the issue. I am attaching the picture for reference.Thank you in advance.

![testing](https://user-images.githubusercontent.com/45798709/234588525-4125ec67-2258-4bb8-92e6-76565f502418.png)

**Comment by Tombana** [comment]
You'll have to get an OS for your raspberry pi with a newer glibc, such as (probably) Manjaro or Arch.

The alternative was to build the code with an older compiler so that it does not depend on the new glibc anymore. Unfortunately using an older crosscompiler in bazel is not so easy. That leaves the option of building it on the raspberry pi itself, but that gave the "empty bazel-bin" issue.

**Comment by sandeep1404** [comment]
Hi @Tombana, So that means should I use Manjaro OS on my raspberry pi? If I use the OS should I build the files again and generate the .whl file or I can use the .whl file generated and can do pip install  ./filename.whl, I hope since the packages are built upon linux-aarch64, the older .whl file should work is it right? 

Now after installing the manjaro OS on my RPI, I will install the LCE with the earlier generated .whl file and perform inference is this correct please correct me if I am wrong, or can I use the current OS and resolve the issue of  GLIBC, if I use the older compiler then you mentioned it will give "empty bazel-bin" issue. So the best option is to go with new OS is it so?

**Comment by Tombana** [comment]
That is all correct. You can use Manjaro OS on our Raspberry Pi. If you go to https://manjaro.org/download/ you can select Raspberry Pi as device and then choose a desktop environment. You can use the `.whl` file that you built before; there is no need to rebuild it.

**Comment by sandeep1404** [comment]
Thanks @Tombana It is working with Manjaro OS, Finally BNN inference is done on RPI using LCE. Really appreciate your continuous help and patience.

**Comment by sandeep1404** [comment]
Hi @Tombana I have a question related to flags in LCE interpreter, when I call the interpreter as mentioned below
```
larq_compute_engine.testing.Interpreter(
    flatbuffer_model,
    num_threads=1,
    use_reference_bconv=False,
    use_indirect_bgemm=False,
    use_xnnpack=False,
)
```
What are the different flags here like ```use_reference_bconv``` , ```use_indirect_bgemm``` and ```use_xnnpack``` and one more question is related to ```num_threads```, I got to know that raspberry pi has 4 cores and it supports multithreading, so for ``` num_threads=1``` I am getting inference of ```0.12s``` for a batch of 8 images while when I set ``` num_threads=2``` or  ``` num_threads=3``` or ``` num_threads=4``` the inference time for all 3 different cases is same almost it is ```0.1s``` for a batch of 8 images, why is it so, as the number of threads increases the design becomes more parallel and inference should be faster, please correct me If I am wrong, what is the maximum value of  ``` num_threads``` we can assign for raspberry pi 4. Thank you in advance.

**Comment by Tombana** [comment]
- `use_reference_bconv` should be left to `False`. It is only used for unittests and uses a slow implementation
- `use_indirect_bgemm` can often result in faster inference for binary layers, so you should try both options and see which one is faster
- `use_xnnpack` specifies if XNNPACK should be used to run all the non-binary layers. Usually it's faster to enable it, but again it should be tested.

As for `num_threads`, you are right that it should become faster if you use more threads, and it should be at most 4.
However it does not use the threads across the batch dimension, it uses threads for each individual input in the batch.
It is common that you don't get a 4X speedup with 4 threads: if the input sizes are not large enough, there is a lot of overhead from parts of the computation that are not parallelized.

**Comment by sandeep1404** [comment]
Hi @Tombana Thank you for your suggestions, I Will try using ```lce_benchmark_model ``` again and observe the results

**Comment by chartain02** [comment]
> Hi @Tombana Thank you for your suggestions, I Will try using `lce_benchmark_model ` again and observe the results

so is this compulsory to install other OS? cant we do this on Raspbian OS?

**Comment by Tombana** [comment]
It will probably work on newer versions of Raspbian OS if they update the gcc/glibc version.

**Comment by chartain02** [comment]
its showing error with python 3.8.10 if i want to install .whl file on raspbian os......it says python 3.8.10 not included in the >=3.10.......in your example it was working with python 3.9 as well

**Comment by Tombana** [comment]
We always support the 3 most recent Python versions, so in this case that is `3.10`, `3.11`, `3.12`. Python 3.8 and 3.9 are no longer supported in the latest release.

**Comment by Tombana** [comment]
You have to [install the wheel package by running `pip install wheel`](https://www.google.com/search?q=bdist_wheel ).

**Comment by chartain02** [comment]
> You have to [install the wheel package by running `pip install wheel`](https://www.google.com/search?q=bdist_wheel).

can you please provide me any script for minimal.cc that we can use for input output of imagenet or any dataset
